In [20]:
from qpsychometric.questionnaire_validator import QuestionnaireValidator
from qpsychometric.personality_traits.compassion_scale import compassion_scale_questionnaire

In [21]:
# Import CS questions
cs_qmnli_df = compassion_scale_questionnaire['QMNLI']
cs_questions = cs_qmnli_df.get_questions()



cs_factors = list(set([q()._descriptor['Factor'] for q in cs_questions]))


# Define CS factors
# cs_factors = [
#     "Kindness",
#     "Common Humanity",
#     "Mindfulness",
#     "Indifference",
#     "Separation",
#     "Disengagement"
# ]

In [ ]:
# Create validator instance
validator = QuestionnaireValidator(
    questionnaire_name="CS",
    questions=cs_questions,
    factors=cs_factors,
    result_path="results/",
    update=True
)

### Get Results For a Single Question

In [23]:
# semantic_results = validator.get_semantic_similarity(cs_questions[0]())
# cola_results = validator.get_cola_score(cs_questions[0]())
# semantic_results, cola_results

### Evaluate a Single Question

In [ ]:
# question_to_evaluate = cs_questions[0] # first question
# # Create validator instance
# validator = QuestionnaireValidator(
#     questionnaire_name="CS",
#     questions=[question_to_evaluate],
#     factors=cs_factors,
#     result_path="results/",
#     update=True
# )

Loading validation models...

/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py:560: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Models loaded successfully.
Splitting 1 questions...
Generated 8 question variants.
Initialized CS Validator:
  - Questions: 1
  - Factors: ['Disengagement', 'Indifference', 'Mindfulness', 'Separation', 'Common Humanity', 'Kindness']
  - Scales: ['frequency']
  - Index: ['index']
  - Device: 0
  - Result path: results

In [25]:

results = validator.run_validation()

======================================================================
Running Complete Validation for CS Questionnaire
======================================================================

Running model evaluation with 8 question variants...

Evaluating models:   0%|          | 0/20 [00:00<?, ?it/s]

Evaluating model: typeform/distilbert-base-uncased-mnli

The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:16<00:00,  2.12s/it]
Evaluating models:   5%|▌         | 1/20 [00:17<05:31, 17.44s/it]

Evaluating model: typeform/mobilebert-uncased-mnli

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  5.31it/s]
Evaluating models:  10%|█         | 2/20 [00:21<02:51,  9.51s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: MoritzLaurer/DeBERTa-v3-large-mnli-fever-anli-ling-wanli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  4.19it/s]
Evaluating models:  15%|█▌        | 3/20 [00:25<01:56,  6.85s/it]

Evaluating model: cross-encoder/nli-deberta-base

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  4.85it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  20%|██        | 4/20 [00:27<01:23,  5.20s/it]

Evaluating model: MoritzLaurer/mDeBERTa-v3-base-mnli-xnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  4.84it/s]
Evaluating models:  25%|██▌       | 5/20 [00:30<01:05,  4.38s/it]

Evaluating model: cross-encoder/nli-MiniLM2-L6-H768

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  4.75it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  30%|███       | 6/20 [00:33<00:51,  3.69s/it]

Evaluating model: navteca/bart-large-mnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  5.41it/s]
Evaluating models:  35%|███▌      | 7/20 [00:36<00:45,  3.49s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: digitalepidemiologylab/covid-twitter-bert-v2-mnli

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  5.14it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  40%|████      | 8/20 [00:38<00:39,  3.26s/it]

Evaluating model: joeddav/bart-large-mnli-yahoo-answers

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  5.31it/s]
Evaluating models:  45%|████▌     | 9/20 [00:41<00:35,  3.20s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: Narsil/deberta-large-mnli-zero-cls

Some weights of the model checkpoint at Narsil/deberta-large-mnli-zero-cls were not used when initializing DebertaForSequenceClassification: ['config']
- This IS expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  5.17it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  50%|█████     | 10/20 [00:45<00:31,  3.16s/it]

Evaluating model: joeddav/xlm-roberta-large-xnli

Some weights of the model checkpoint at joeddav/xlm-roberta-large-xnli were not used when initializing XLMRobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  5.36it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  55%|█████▌    | 11/20 [00:49<00:31,  3.51s/it]

Evaluating model: katanemo/bart-large-mnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  4.44it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  60%|██████    | 12/20 [00:52<00:28,  3.54s/it]

Evaluating model: mjwong/e5-large-mnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  5.33it/s]
Evaluating models:  65%|██████▌   | 13/20 [00:55<00:22,  3.19s/it]

Evaluating model: mjwong/multilingual-e5-large-xnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  5.26it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  70%|███████   | 14/20 [00:59<00:20,  3.46s/it]

Evaluating model: navteca/nli-deberta-v3-large

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  4.38it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  75%|███████▌  | 15/20 [01:03<00:17,  3.56s/it]

Evaluating model: symanto/mpnet-base-snli-mnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  5.52it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  80%|████████  | 16/20 [01:05<00:12,  3.09s/it]

Evaluating model: valhalla/distilbart-mnli-12-6

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  5.22it/s]
Evaluating models:  85%|████████▌ | 17/20 [01:07<00:08,  2.99s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: facebook/bart-large-mnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  5.38it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  90%|█████████ | 18/20 [01:10<00:05,  3.00s/it]

Evaluating model: utahnlp/mnli_microsoft_deberta-v3-large_seed-3

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  4.31it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  95%|█████████▌| 19/20 [01:14<00:03,  3.06s/it]

Evaluating model: FacebookAI/roberta-large-mnli

Some weights of the model checkpoint at FacebookAI/roberta-large-mnli were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 8/8 [00:01<00:00,  4.58it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models: 100%|██████████| 20/20 [01:17<00:00,  3.88s/it]

✓ Model evaluation complete. Results saved to: results/cs_mnli_results.csv

======================================================================
Calculating Content Validity Metrics
======================================================================

✓ Content validity metrics saved to: results/linguistic_acceptability.csv

Content Validity Results:
                  semantic_similarity  cola_score  silhouette_score
Q
CSDisengagement1             0.866993    0.966075          0.302997

======================================================================
Calculating Internal Consistency (Cronbach's Alpha)
======================================================================

Cronbach Alpha:
Disengagement: Insufficient items (n=1)
Indifference: Insufficient items (n=0)
Mindfulness: Insufficient items (n=0)
Separation: Insufficient items (n=0)
Common Humanity: Insufficient items (n=0)
Kindness: Insufficient items (n=0)

CS Overall: Insufficient items

======================================================================
Calculating Factor Correlations
======================================================================

✓ Factor correlations (spearman):
              Disengagement   CS
Disengagement             -  ***
CS                      1.0    -

======================================================================
Validation Complete!
======================================================================
Results saved in: results

In [26]:
validator = QuestionnaireValidator(
    questionnaire_name="CS",
    questions=cs_questions,
    factors=cs_factors,
    result_path="results/",
)

# Returns a DataFrame for all questions — no MNLI models needed
semantic_df = validator.get_semantic_similarity()   # q=None → all questions
cola_df = validator.get_cola_score()                # q=None → all questions

# Merge into a single content validity view
import pandas as pd
content_validity = semantic_df.join(cola_df)
content_validity

Loading validation models...

/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py:560: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Models loaded successfully.
Splitting 24 questions...
Generated 192 question variants.
Initialized CS Validator:
  - Questions: 24
  - Factors: ['Disengagement', 'Indifference', 'Mindfulness', 'Separation', 'Common Humanity', 'Kindness']
  - Scales: ['frequency']
  - Index: ['index']
  - Device: 0
  - Result path: results

Calculating semantic similarity: 100%|██████████| 24/24 [00:21<00:00,  1.11it/s]
Calculating COLA scores: 100%|██████████| 24/24 [00:17<00:00,  1.37it/s]

                     semantic_similarity  cola_score
CSDisengagement1                0.866993    0.966075
CSIndifference2                 0.935983    0.884835
CSSeparation3                   0.877832    0.957124
CSMindfulness4                  0.988526    0.978119
CSSeparation5                   0.992628    0.909294
CSKindness6                     0.650216    0.906795
CSDisengagement7                0.718459    0.970024
CSKindness8                     0.546249    0.638818
CSMindfulness9                  0.903150    0.905713
CSSeparation10                  0.933394    0.888272
CSCommon Humanity11             0.787442    0.898494
CSIndifference12                0.380992    0.912104
CSMindfulness13                 0.993413    0.761378
CSIndifference14                0.742188    0.828846
CSCommon Humanity15             0.847258    0.970311
CSKindness16                    0.664441    0.887123
CSCommon Humanity17             0.676063    0.970970
CSIndifference18                0.721551    0.951308
CSDisengagement19               0.711748    0.973909
CSCommon Humanity20             0.960301    0.969589
CSMindfulness21                 0.929275    0.935093
CSSeparation22                  0.988580    0.956959
CSDisengagement23               0.931498    0.978627
CSKindness24                    0.731850    0.914375

In [27]:
results.keys()

dict_keys(['results_csv', 'content_validity', 'cronbach_alpha', 'correlations'])

In [28]:
results['results_csv']

PosixPath('results/cs_mnli_results.csv')

In [29]:
results['content_validity']

                  semantic_similarity  cola_score  silhouette_score
Q
CSDisengagement1             0.866993    0.966075          0.302997

In [30]:
results['cronbach_alpha']["overall"]

In [31]:
results['cronbach_alpha']["factors"]

{}

In [32]:
data_df = results['cronbach_alpha']['data_df']
validator.test_question_affect_on_cronbach_alpha(data_df, specific_factors=['Kindness'])

AssertionError: At least two items are required.

In [ ]:
data_df

Q,CSCommon Humanity11,CSCommon Humanity15,CSCommon Humanity17,CSCommon Humanity20,CSDisengagement1,CSDisengagement19,CSDisengagement23,CSDisengagement7,CSIndifference12,CSIndifference14,...,CSKindness6,CSKindness8,CSMindfulness13,CSMindfulness21,CSMindfulness4,CSMindfulness9,CSSeparation10,CSSeparation22,CSSeparation3,CSSeparation5
model,,,,,,,,,,,,,,,,,,,,,
Narsil/deberta-large-mnli-zero-cls,0.030071,0.071995,0.078060,0.035680,0.007929,0.014338,0.018115,0.015700,0.044705,0.065681,...,0.083942,0.081510,0.063152,0.050293,0.063118,0.042474,0.081483,0.101515,0.035494,0.101259
cross-encoder/nli-MiniLM2-L6-H768,0.057885,0.065096,0.065243,0.050079,0.057108,0.016218,0.047265,0.058561,0.019081,0.025546,...,0.054330,0.047081,0.053287,0.031459,0.040160,0.046837,0.093654,0.128763,0.123809,0.055802
cross-encoder/nli-deberta-base,0.065087,0.077900,0.074281,0.052726,0.039844,0.042052,0.028367,0.061726,0.033522,0.031002,...,0.077636,0.076146,0.049050,0.038678,0.037900,0.043783,0.121803,0.119583,0.112517,0.116179
digitalepidemiologylab/covid-twitter-bert-v2-mnli,0.062018,0.058788,0.078296,0.050901,-0.014296,0.023190,0.030217,-0.013344,0.057273,-0.008810,...,0.080042,0.057771,0.072111,0.046322,0.067645,0.046021,0.088564,0.125419,-0.004869,0.087402
joeddav/bart-large-mnli-yahoo-answers,0.008295,0.014450,0.015103,0.003930,-0.002338,0.011231,-0.000096,0.003795,-0.000738,-0.001173,...,0.025344,0.026315,0.025012,0.010308,0.008933,0.010720,0.006113,0.006591,0.006152,0.030862
microsoft/deberta-base-mnli,0.012361,0.073699,0.073939,0.036110,0.055728,0.019291,0.046230,0.073161,0.030104,0.039943,...,0.092614,0.084013,0.067720,0.045512,0.050252,0.027581,0.157336,0.158261,0.058583,0.158952
microsoft/deberta-large-mnli,0.030071,0.071995,0.078060,0.035680,0.007929,0.014338,0.018115,0.015700,0.044705,0.065681,...,0.083942,0.081510,0.063152,0.050293,0.063118,0.042474,0.081483,0.101515,0.035494,0.101259
navteca/bart-large-mnli,0.043513,0.074674,0.082026,0.039156,0.005940,0.061748,0.036957,0.052043,0.018426,0.012320,...,0.099218,0.097514,0.077620,0.050363,0.007123,0.028248,0.138846,0.146322,0.152090,0.168685
typeform/distilbert-base-uncased-mnli,0.063071,0.086961,0.071782,0.052295,0.081472,0.067785,0.089825,0.087475,0.030962,0.032872,...,0.042490,0.055197,0.065664,0.029688,0.068475,0.043434,0.155539,0.122632,0.174462,0.118264
typeform/mobilebert-uncased-mnli,0.065015,0.074768,0.060298,0.042086,0.046891,-0.000307,0.061923,0.050281,0.050051,0.000705,...,0.085505,0.085614,0.053527,0.025134,0.047340,0.005009,0.124983,0.141621,0.124329,0.061937
valhalla/distilbart-mnli-12-6,0.061487,0.076169,0.075674,0.037537,0.008704,0.020253,0.044601,0.028450,0.048093,0.030168,...,0.088780,0.087052,0.050260,0.062305,0.012930,0.013713,0.117013,0.081574,0.096824,0.139522

In [ ]:
results['correlations']

,Disengagement,Common Humanity,Mindfulness,Separation,Kindness,Indifference,CS
Disengagement,-,,,**,,,**
Common Humanity,0.379,-,,,,,
Mindfulness,-0.014,0.059,-,,,,
Separation,0.799,0.434,-0.16,-,,,***
Kindness,0.123,-0.041,-0.16,0.489,-,,
Indifference,0.233,0.032,0.151,0.361,0.562,-,
CS,0.845,0.479,-0.123,0.991,0.406,0.352,-