# Imports

In [1]:
!pip install pingouin
!pip install qlatent
%pip install --quiet git+https://github.com/cnai-lab/qpsychometric.git

Collecting pingouin
  Downloading pingouin-0.5.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from pingouin) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pingouin) (2.0.2)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.12/dist-packages (from pingouin) (2.2.2)
Collecting pandas-flavor (from pingouin)
  Downloading pandas_flavor-0.7.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: scikit-learn>=1.2 in /usr/local/lib/python3.12/dist-packages (from pingouin) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pingouin) (1.16.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from pingouin) (0.13.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from pingouin) (0.14.5)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from pingouin) (0.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5->pingouin) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5->pingouin) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5->pingouin) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2->pingouin) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2->pingouin) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (3.2.5)
Requirement already satisfied: xarray in /usr/local/lib/python3.12/dist-packages (from pandas-flavor->pingouin) (2025.10.1)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pingouin) (1.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5->pingouin) (1.17.0)
Downloading pingouin-0.5.5-py3-none-any.whl (204 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.4/204.4 kB 6.2 MB/s eta 0:00:00
Downloading pandas_flavor-0.7.0-py3-none-any.whl (8.4 kB)
Installing collected packages: pandas-flavor, pingouin
Successfully installed pandas-flavor-0.7.0 pingouin-0.5.5
Collecting qlatent
  Downloading qlatent-1.0.23-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from qlatent) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from qlatent) (2.2.2)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from qlatent) (0.13.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from qlatent) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from qlatent) (1.6.1)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from qlatent) (4.57.1)
Requirement already satisfied: pingouin in /usr/local/lib/python3.12/dist-packages (from qlatent) (0.5.5)
Requirement already satisfied: typeguard in /usr/local/lib/python3.12/dist-packages (from qlatent) (4.4.4)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from qlatent) (4.0.0)
Collecting evaluate (from qlatent)
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from qlatent) (3.10.0)
Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.12/dist-packages (from qlatent) (5.1.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets->qlatent) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->qlatent) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->qlatent) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets->qlatent) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets->qlatent) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->qlatent) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->qlatent) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->qlatent) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets->qlatent) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets->qlatent) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets->qlatent) (6.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->qlatent) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->qlatent) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->qlatent) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->qlatent) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->qlatent) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->qlatent) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->qlatent) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->qlatent) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->qlatent) (2025.2)
Requirement already satisfied: pandas-flavor in /usr/local/lib/python3.12/dist-packages (from pingouin->qlatent) (0.7.0)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from pingouin->qlatent) (0.14.5)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from pingouin->qlatent) (0.9.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->qlatent) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->qlatent) (3.6.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers->qlatent) (2.8.0+cu126)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers->qlatent) (4.15.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->qlatent) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->qlatent) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->qlatent) (0.6.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->qlatent) (3.13.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets->qlatent) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->qlatent) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->qlatent) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->qlatent) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->qlatent) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->qlatent) (2025.10.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers->qlatent) (3.4.0)
Requirement already satisfied: xarray in /usr/local/lib/python3.12/dist-packages (from pandas-flavor->pingouin->qlatent) (2025.10.1)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pingouin->qlatent) (1.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->qlatent) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->qlatent) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->qlatent) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->qlatent) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->qlatent) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->qlatent) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->qlatent) (1.22.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers->qlatent) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence_transformers->qlatent) (3.0.3)
Downloading qlatent-1.0.23-py3-none-any.whl (914 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 914.1/914.1 kB 19.2 MB/s eta 0:00:00
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.6 MB/s eta 0:00:00
Installing collected packages: evaluate, qlatent
Successfully installed evaluate-0.4.6 qlatent-1.0.23
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 95.0 MB/s eta 0:00:00
  Building wheel for qpsychometric (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.

In [2]:
import torch
import pandas as pd
from pathlib import Path
import gc
from tqdm.auto import tqdm
import warnings
import pingouin as pg
from sentence_transformers import SentenceTransformer, util
from pathlib import Path
import json, torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.utils.data import DataLoader
from tqdm import tqdm
import numpy as np
from qlatent.qmnli.qmnli import *
from qlatent.qmnli.qmnli import _QMNLI, QMNLI
device = 0 if torch.cuda.is_available() else -1
print(device)

0

In [3]:
softmax_files = [True, False]

def split_question(Q, index, scales, softmax, filters):
  result = []
  for s in scales:
    q = QCACHE(Q())
    for sf in softmax:
      for f in filters:
        if sf:
            qsf = QSOFTMAX(q,dim=[index[0], s])
            qsf_f = QFILTER(qsf,filters[f],filtername=f)
            print((index, s),sf,f)
            result.append(qsf_f)

            qsf = QSOFTMAX(q,dim=s)
            qsf_f = QFILTER(qsf,filters[f],filtername=f)
            print(s,sf,f)
            result.append(qsf_f)

            qsf = QSOFTMAX(q,dim=index[0])
            qsf_f = QFILTER(qsf,filters[f],filtername=f)
            print(index[0],sf,f)
            result.append(qsf_f)
        else:
            qsf = QPASS(q,descupdate={'softmax':''})
            qsf_f = QFILTER(qsf,filters[f],filtername=f)
            print(s,sf,f)
            result.append(qsf_f)
  return result


def print_permutations(q):
#     for q in Q1s:
    W = q._pdf['W']
    print(q._descriptor)
    for i, (kmap, w) in enumerate(zip(q._keywords_map, W)):
        context = q._context_template.format_map(kmap)
        answer = q._answer_template.format_map(kmap)
#         sexisem_score = sexisem_classifier(context.strip('.') + ' ' +answer)
        print(f'{i}.',context ,'->', answer, w)
#     break


frequency_weights:SCALE = {
    'never':-4,
    'very rarely':-3,
    'seldom':-2,
    'rarely':-2,
    'frequently':2,
    'often':2,
    'very frequently':3,
    'always':4,
}

intensifiers_fraction_without_none:SCALE={
            "few":1,
            "some":2,
            "many":3,
            "most":4,
            "all":5,
        }

certainty_weights:SCALE = {
    "isn't":-2,
    "can't be":-2,
    "isn't probably":-1,
    'is probably':1,
    'can be':1,
    'is':2,
}

# Load Models

In [4]:
p = 'valhalla/distilbart-mnli-12-6'
mnli = pipeline("zero-shot-classification",device=device, model=p)
mnli.model_identifier = p

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.23G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.23G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

Device set to use cuda:0

In [5]:
gc.collect()
torch.cuda.empty_cache()

123

# Linguastic acceptability

In [6]:
sentence_embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
cola = pipeline("text-classification","mrm8488/deberta-v3-small-finetuned-cola", device=device)

import os
import pandas as pd
from nltk.translate.bleu_score import sentence_bleu

def linguistic_acceptabilities(q, index, scale, question_name, student_id, output_path=Path(''), save_to_file=False):
    score_by_cola_lst=[]
    score_of_semantic_distance_lst=[]
    score_by_bleu_lst=[]
    kmap_lst=[]
    question_name_lst=[]
    description = q._descriptor
    strFactor=description['Factor']
    strOrdinal=str(description.get('Ordinal', 0))
    ##cleaning the string to get the original question
    strOriginal= description['Original']
    strOriginal = 'none' if strOriginal is None else strOriginal
    strOriginal=strOriginal.replace(strFactor,'',1)
    strOriginal=strOriginal.replace(strOrdinal,'',1)
    strOriginal=strOriginal.replace('.','',1)
    strOriginal=strOriginal.strip() #the original question
    rows = []

    partial_internal_consistency = partial(q.internal_consistency, filter={}, index=index , scale=scale)
    try:
        silhouette_score = partial_internal_consistency(measure='silhouette_score', metric='correlation')
    except Exception as e:
        print(e)
        print('silhouette_score is set to -1')
        silhouette_score = -1

    if hasattr(q, 'linguistic_acceptability'):
        q.linguistic_acceptability['silhouette_score'] = silhouette_score
        return q.linguistic_acceptability

    for kmap in q._keywords_map:
        score = {}
        score['question_name'] = question_name
        context = q._context_template.format_map(kmap)
        answer = q._answer_template.format_map(kmap)
        score['original_question'] = strOriginal


        cola_score = cola(context +" "+ answer)[0].get('score')
        score['cola_score'] = cola_score
        score['param'] = kmap
        strPermutation= context +" "+ answer
        # sentences = [context +" "+ answer]
        score['question_permutation'] = strPermutation
        #Compute embedding for both lists
        embeddings1 = sentence_embedding_model.encode(strOriginal, convert_to_tensor=True)
        embeddings2 = sentence_embedding_model.encode(strPermutation, convert_to_tensor=True)

        #Compute cosine-similarities
        cosine_scores = util.cos_sim(embeddings1, embeddings2)
        score['semantic_similarity'] = cosine_scores.item()

        score['silhouette_score'] = silhouette_score
        rows.append(score)


    filename = output_path / 'linguistic_acceptabilities.csv'
    df = pd.DataFrame(rows)
    df['student_id'] = student_id
    df = df[['student_id', 'question_name','original_question', 'param','question_permutation','cola_score','semantic_similarity','silhouette_score']]
    if save_to_file:
        if filename.exists():
            df.to_csv(filename, index=False, header=None, mode='a', encoding='utf-8-sig')
        else:
            df.to_csv(filename, index=False, encoding='utf-8-sig')
#     print(f"Linguistic acceptabilities saved in {filename}")
    q.linguistic_acceptability = df
    return df

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/568M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/393 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/18.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Device set to use cuda:0

#import questionaire

In [15]:
from qpsychometric.mental_health.sense_of_coherence import soc_questionnaire
from qpsychometric.mental_health.sense_of_coherence.soc_qmnli import SOCQ9

soc_qmnli_df = soc_questionnaire['QMNLI']
soc_questions = soc_qmnli_df.get_questions()

# map class name -> class
_name2cls = {Q.__name__: Q for Q in soc_questions}

# bind the exact classes you want (order matters; index 0 == SOCQ4)
SOCQ4  = _name2cls["SOCQ4"]
SOCQ5  = _name2cls["SOCQ5"]
SOCQ6  = _name2cls["SOCQ6"]
SOCQ8  = _name2cls["SOCQ8"]
SOCQ12 = _name2cls["SOCQ12"]
SOCQ16 = _name2cls["SOCQ16"]
SOCQ19 = _name2cls["SOCQ19"]
SOCQ21 = _name2cls["SOCQ21"]
SOCQ25 = _name2cls["SOCQ25"]
SOCQ26 = _name2cls["SOCQ26"]
SOCQ28 = _name2cls["SOCQ28"]
SOCQ29 = _name2cls["SOCQ29"]

# --- splits (frequency everywhere), plus your positiveonly filter ---
Q4s  = split_question(SOCQ4,  index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ4().get_filter_for_postive_keywords(['frequency'])})
Q5s  = split_question(SOCQ5,  index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ5().get_filter_for_postive_keywords(['frequency'])})
Q6s  = split_question(SOCQ6,  index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ6().get_filter_for_postive_keywords(['frequency'])})
Q8s  = split_question(SOCQ8,  index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ8().get_filter_for_postive_keywords(['frequency'])})
Q9s = split_question(SOCQ9, index=["index"], scales=["frequency"], softmax=softmax_files,
                     filters={'unfiltered':{}, "positiveonly": SOCQ9().get_filter_for_postive_keywords(['frequency'])})
Q12s = split_question(SOCQ12, index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ12().get_filter_for_postive_keywords(['frequency'])})
Q16s = split_question(SOCQ16, index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ16().get_filter_for_postive_keywords(['frequency'])})
Q19s = split_question(SOCQ19, index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ19().get_filter_for_postive_keywords(['frequency'])})
Q21s = split_question(SOCQ21, index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ21().get_filter_for_postive_keywords(['frequency'])})
Q25s = split_question(SOCQ25, index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ25().get_filter_for_postive_keywords(['frequency'])})
Q26s = split_question(SOCQ26, index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ26().get_filter_for_postive_keywords(['frequency'])})
Q28s = split_question(SOCQ28, index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ28().get_filter_for_postive_keywords(['frequency'])})
Q29s = split_question(SOCQ29, index=["index"], scales=["frequency"], softmax=softmax_files,
                      filters={'unfiltered':{}, "positiveonly": SOCQ29().get_filter_for_postive_keywords(['frequency'])})

(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly
(['index'], 'frequency') True unfiltered
frequency True unfiltered
index True unfiltered
(['index'], 'frequency') True positiveonly
frequency True positiveonly
index True positiveonly
frequency False unfiltered
frequency False positiveonly

# Run Questionnaires on models

## Utility functions

In [8]:
def question_attributes(q):
    score = {}
    score['questionnair']=q._descriptor['Questionnair']
    score['factor']=q._descriptor['Factor']
    score['ordinal']=q._descriptor['Ordinal']
    score['scale']=q._descriptor['scale']
    score['index']=q._descriptor['index']
    score['filter']=q._descriptor['filter']
    score['softmax'] = q._descriptor['softmax']
    score["original"] = q._descriptor['Original']
    score['Q'] = f"{score['questionnair']}{score['factor']}{score['ordinal']}"
    score['context_template'] = q._context_template
    score['answer_template'] = q._answer_template
    score['dimensions'] = q._dimensions
    score['model'] = q.model.model_identifier if q.model else ""
    return score

def get_question_features(q, student_id='student_id', output_path=Path(''), save_to_file=False):
    score = question_attributes(q)
    score['mean_score'] = q.mean_score()
    index= q._index
    scale= q._scale
    linguistic_df = linguistic_acceptabilities(q, index=index, scale=scale,question_name=score['Q'], student_id=student_id,
                                               output_path=output_path, save_to_file=save_to_file)
    row = linguistic_df[['cola_score','silhouette_score']].mean(axis=0)
    row_dict = dict(row)
    row_dict['semantic_similarity'] = linguistic_df['semantic_similarity'].quantile(0.75)
    score = score | row_dict
    return score

def extract_epoch(model_path):
    if 'epoch-' in model_path.name:
        i = model_path.name.find('epoch-')
        j = model_path.name.find('_', i)
        if j > 0:
            epoch = int(model_path.name[i+len('epoch-'):j])
        else:
            epoch = int(model_path.name[i+len('epoch-'):])

    elif 'checkpoint-' in model_path.name:
        i = model_path.name.find('checkpoint-')
        j = model_path.name.find('_', i)
        if j > 0:
            epoch = int(model_path.name[i+len('checkpoint-'):j])
        else:
            epoch = int(model_path.name[i+len('checkpoint-'):])
    else:
        epoch = 0
    return epoch

def extract_run(model_path):
    try:
        if 'run' in model_path.name:
            for part in model_path.name.split('_'):
                if 'run' in part:
                    return int(part.replace('run', ''))
        else:
            return -1
    except Exception as e:
        print(e)
        return -1

import json

def get_mnli_score(checkpoint_path):
    mnli_score_path = checkpoint_path / 'all_results.json'
    if not mnli_score_path.exists():
        mnli_score_path = checkpoint_path.parent / (checkpoint_path.name + '_mnli_eval') / 'all_results.json'
    if mnli_score_path.exists():
        with open(mnli_score_path) as f:
            return json.load(f)["eval_accuracy"]
    else:
        return -1


def run_questions(questions, mnli_checkpoint, train_process, fintune_dataset, q_range=[5, 0]):
    rows = []
    checkpoint = Path(mnli_checkpoint.model_identifier)
    for q_raw in tqdm(questions):
        T = time.time()
        q = q_raw.run(mnli_checkpoint)
        T = time.time()
        score = get_question_features(q)
        score['epoch'] = extract_epoch(checkpoint)
        score['train_process'] = train_process
        score['dataset'] = fintune_dataset
        score['run'] = extract_run(checkpoint.parent)
        score['mnli_score'] = get_mnli_score(checkpoint)
        score['range'] = (q._weights_flat.min(), q._weights_flat.max())
        score['ASI_score'] = np.interp(score['mean_score'], [q._weights_flat.min(), q._weights_flat.max()], q_range)
        rows.append(score)
        gc.collect()
        torch.cuda.empty_cache()
    return rows


def calc_scores(questions, checkpoint, output_path, train_process, fintune_dataset, q_range=[5, 0]):
    fix_config(checkpoint)
    mnli_checkpoint = pipeline("zero-shot-classification", str(checkpoint), device=device)
    mnli_checkpoint.model_identifier = str(checkpoint)
    rows = run_questions(questions, mnli_checkpoint, train_process, fintune_dataset=fintune_dataset, q_range=q_range)
    return rows

def add_epochs_to_rows(rows, mlm_epoch, mnli_checkpoint):
    for score in rows:
        score['mlm_epoch'] = mlm_epoch
        score['mnli_checkpoint'] = mnli_checkpoint
    return rows


def write_to_csv(rows, output_path):
    old_score_hostile_df = pd.DataFrame(rows)
    if output_path.exists():
        old_score_hostile_df.to_csv(output_path, index=False, header=None, mode='a')
    else:
        old_score_hostile_df.to_csv(output_path, index=False)

def fix_config(checkpoint):
    if checkpoint.exists():
        with open(checkpoint / 'config.json') as f:
            d1 = json.load(f)
        d1['id2label'] = {'0': 'entailment', '1': 'neutral', '2': 'contradiction'}
        d1['label2id'] = {'contradiction': 2, 'entailment': 0, 'neutral': 1}
        with open(checkpoint / 'config.json', 'w') as f:
            json.dump(d1, f)
    else:
        print(checkpoint, '#### Not exists ####')

def calc_for_all_models(Qs, q_range= [5, 0]):
    all_rows = []
    for p in tqdm(mnli_pipelines):
        print(p)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            rows = calc_scores(Qs, Path(p),  Path(p), '->'.join(['base']), 'hostile',
                               use_base_model=False, q_range=q_range)
            rows = add_epochs_to_rows(rows, 0, 0)
            all_rows += rows
    return pd.DataFrame(all_rows)

## Run Questions

In [9]:
result_path = Path('results/')
if not result_path.exists():
    os.makedirs(result_path)

In [12]:
mnli_pipelines = [
    'typeform/distilbert-base-uncased-mnli',
    'typeform/mobilebert-uncased-mnli',
    'cross-encoder/nli-roberta-base',
    'cross-encoder/nli-deberta-base',
    'cross-encoder/nli-distilroberta-base',
    'cross-encoder/nli-MiniLM2-L6-H768',
    'navteca/bart-large-mnli',
    'digitalepidemiologylab/covid-twitter-bert-v2-mnli',
    'joeddav/bart-large-mnli-yahoo-answers',
    'Narsil/deberta-large-mnli-zero-cls',
    'microsoft/deberta-large-mnli',
    'microsoft/deberta-base-mnli',
    'Alireza1044/albert-base-v2-mnli',
    'yoshitomo-matsubara/bert-large-uncased-mnli',
    'yoshitomo-matsubara/bert-base-uncased-mnli',
    'yoshitomo-matsubara/bert-base-uncased-mnli_from_bert-large-uncased-mnli',
    'valhalla/distilbart-mnli-12-6',
]

In [ ]:
from collections import defaultdict

questions = Q4s + Q5s + Q16s + Q21s + Q25s + Q28s + Q29s
questions +=  Q6s + Q12s + Q9s + Q8s + Q19s + Q26s

update = True

output_path = result_path / f'soc_mnli_check1.csv'
pipelines = mnli_pipelines

if output_path.exists():
    temp_df = pd.read_csv(output_path)
    indexes = temp_df.groupby(['model', 'Q']).count().index.values
    used_models = defaultdict(set)
    for k, v in indexes:
        used_models[k].add(v)
else:
    used_models = {}


for p in tqdm(pipelines):
    print(p)
    if get_mnli_score(Path(p)) < 0.7 and p not in mnli_pipelines:
        print('Skip:', p)
        continue
    with warnings.catch_warnings():
        try:
            warnings.simplefilter("ignore")
            if p in used_models and not update:
                pipline_questions = []
                for q in questions:
                    if question_attributes(q)['Q'] not in used_models[p]:
                        pipline_questions.append(q)
                    else:
                        print('skip', p, question_attributes(q)['Q'])
            else:
                pipline_questions = questions

            rows = calc_scores(pipline_questions, Path(p),  output_path, '->'.join(['base']), 'hostile',)
            rows = add_epochs_to_rows(rows, 0, 0)
            write_to_csv(rows, output_path)
            gc.collect()
            torch.cuda.empty_cache()
        except Exception as e:
            print(e)


df = pd.read_csv(output_path)
df = df.drop_duplicates(subset=['filter','softmax','model','Q'], keep='last')
df.to_csv(output_path, index=False)

  0%|          | 0/17 [00:00<?, ?it/s]

typeform/distilbert-base-uncased-mnli
typeform/distilbert-base-uncased-mnli #### Not exists ####

Device set to use cuda:0

  0%|          | 0/104 [00:00<?, ?it/s]
  1%|          | 1/104 [00:04<07:33,  4.41s/it]
  2%|▏         | 2/104 [00:09<08:37,  5.07s/it]
  3%|▎         | 3/104 [00:14<07:54,  4.69s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

  4%|▍         | 4/104 [00:19<08:23,  5.03s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

  5%|▍         | 5/104 [00:25<08:31,  5.16s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

  6%|▌         | 6/104 [00:31<09:06,  5.58s/it]
  7%|▋         | 7/104 [00:35<08:00,  4.95s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

  8%|▊         | 8/104 [00:40<08:01,  5.02s/it]
  9%|▊         | 9/104 [00:44<07:42,  4.87s/it]
 10%|▉         | 10/104 [00:47<06:37,  4.23s/it]
 11%|█         | 11/104 [00:49<05:28,  3.54s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 12%|█▏        | 12/104 [00:53<05:27,  3.56s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 12%|█▎        | 13/104 [00:56<05:24,  3.57s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 13%|█▎        | 14/104 [00:58<04:42,  3.14s/it]
 14%|█▍        | 15/104 [01:02<04:58,  3.35s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 15%|█▌        | 16/104 [01:04<04:21,  2.98s/it]
 16%|█▋        | 17/104 [01:11<05:53,  4.06s/it]
 17%|█▋        | 18/104 [01:16<06:02,  4.21s/it]
 18%|█▊        | 19/104 [01:21<06:16,  4.43s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 19%|█▉        | 20/104 [01:26<06:38,  4.75s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 20%|██        | 21/104 [01:30<06:14,  4.51s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 21%|██        | 22/104 [01:36<06:49,  4.99s/it]
 22%|██▏       | 23/104 [01:41<06:39,  4.94s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 23%|██▎       | 24/104 [01:46<06:32,  4.90s/it]
 24%|██▍       | 25/104 [01:51<06:36,  5.03s/it]
 25%|██▌       | 26/104 [01:57<06:43,  5.17s/it]
 26%|██▌       | 27/104 [02:01<06:22,  4.96s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 27%|██▋       | 28/104 [02:06<06:17,  4.97s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 28%|██▊       | 29/104 [02:12<06:38,  5.31s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 29%|██▉       | 30/104 [02:16<06:02,  4.90s/it]
 30%|██▉       | 31/104 [02:20<05:40,  4.66s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 31%|███       | 32/104 [02:26<06:04,  5.07s/it]
 32%|███▏      | 33/104 [02:29<05:06,  4.32s/it]
 33%|███▎      | 34/104 [02:33<04:54,  4.20s/it]
 34%|███▎      | 35/104 [02:36<04:34,  3.97s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 35%|███▍      | 36/104 [02:39<04:10,  3.68s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 36%|███▌      | 37/104 [02:42<03:53,  3.48s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 37%|███▋      | 38/104 [02:44<03:24,  3.09s/it]
 38%|███▊      | 39/104 [02:47<03:03,  2.83s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 38%|███▊      | 40/104 [02:50<03:22,  3.17s/it]
 39%|███▉      | 41/104 [02:55<03:51,  3.67s/it]
 40%|████      | 42/104 [03:00<04:01,  3.89s/it]
 41%|████▏     | 43/104 [03:06<04:36,  4.53s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 42%|████▏     | 44/104 [03:10<04:30,  4.52s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 43%|████▎     | 45/104 [03:16<04:46,  4.85s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 44%|████▍     | 46/104 [03:21<04:38,  4.81s/it]
 45%|████▌     | 47/104 [03:27<05:00,  5.27s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 46%|████▌     | 48/104 [03:31<04:34,  4.91s/it]
 47%|████▋     | 49/104 [03:35<04:14,  4.63s/it]
 48%|████▊     | 50/104 [03:39<04:05,  4.54s/it]
 49%|████▉     | 51/104 [03:44<03:56,  4.46s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 50%|█████     | 52/104 [03:48<03:52,  4.46s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 51%|█████     | 53/104 [03:52<03:36,  4.25s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 52%|█████▏    | 54/104 [03:57<03:45,  4.52s/it]
 53%|█████▎    | 55/104 [04:00<03:15,  3.98s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 54%|█████▍    | 56/104 [04:02<02:43,  3.40s/it]
 55%|█████▍    | 57/104 [04:03<02:13,  2.85s/it]
 56%|█████▌    | 58/104 [04:07<02:19,  3.04s/it]
 57%|█████▋    | 59/104 [04:09<02:05,  2.78s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 58%|█████▊    | 60/104 [04:13<02:14,  3.06s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 59%|█████▊    | 61/104 [04:15<01:57,  2.72s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 60%|█████▉    | 62/104 [04:19<02:10,  3.10s/it]
 61%|██████    | 63/104 [04:21<02:00,  2.94s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 62%|██████▏   | 64/104 [04:23<01:47,  2.69s/it]
 62%|██████▎   | 65/104 [04:26<01:51,  2.86s/it]
 63%|██████▎   | 66/104 [04:30<02:00,  3.18s/it]
 64%|██████▍   | 67/104 [04:35<02:15,  3.66s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 65%|██████▌   | 68/104 [04:38<02:03,  3.44s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 66%|██████▋   | 69/104 [04:43<02:19,  3.98s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 67%|██████▋   | 70/104 [04:47<02:07,  3.76s/it]
 68%|██████▊   | 71/104 [04:51<02:09,  3.93s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 69%|██████▉   | 72/104 [04:55<02:08,  4.00s/it]
 70%|███████   | 73/104 [05:00<02:10,  4.22s/it]
 71%|███████   | 74/104 [05:05<02:13,  4.47s/it]
 72%|███████▏  | 75/104 [05:10<02:14,  4.64s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 73%|███████▎  | 76/104 [05:14<02:06,  4.50s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 74%|███████▍  | 77/104 [05:18<01:57,  4.36s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 75%|███████▌  | 78/104 [05:23<01:58,  4.56s/it]
 76%|███████▌  | 79/104 [05:27<01:52,  4.49s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 77%|███████▋  | 80/104 [05:31<01:41,  4.22s/it]
 78%|███████▊  | 81/104 [05:37<01:46,  4.62s/it]
 79%|███████▉  | 82/104 [05:42<01:46,  4.84s/it]
 80%|███████▉  | 83/104 [05:46<01:36,  4.57s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 81%|████████  | 84/104 [05:51<01:34,  4.74s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 82%|████████▏ | 85/104 [05:57<01:34,  4.98s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 83%|████████▎ | 86/104 [06:02<01:29,  4.97s/it]
 84%|████████▎ | 87/104 [06:06<01:22,  4.83s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 85%|████████▍ | 88/104 [06:11<01:16,  4.78s/it]
 86%|████████▌ | 89/104 [06:15<01:11,  4.75s/it]
 87%|████████▋ | 90/104 [06:19<01:03,  4.55s/it]
 88%|████████▊ | 91/104 [06:22<00:52,  4.01s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 88%|████████▊ | 92/104 [06:28<00:53,  4.43s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 89%|████████▉ | 93/104 [06:31<00:43,  3.99s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 90%|█████████ | 94/104 [06:35<00:41,  4.13s/it]
 91%|█████████▏| 95/104 [06:40<00:40,  4.46s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 92%|█████████▏| 96/104 [06:43<00:32,  4.08s/it]
 93%|█████████▎| 97/104 [06:48<00:28,  4.14s/it]
 94%|█████████▍| 98/104 [06:51<00:23,  3.95s/it]
 95%|█████████▌| 99/104 [06:55<00:20,  4.03s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 96%|█████████▌| 100/104 [06:58<00:14,  3.55s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 97%|█████████▋| 101/104 [07:01<00:10,  3.47s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 98%|█████████▊| 102/104 [07:05<00:07,  3.72s/it]
 99%|█████████▉| 103/104 [07:10<00:03,  3.91s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

100%|██████████| 104/104 [07:12<00:00,  4.16s/it]

0

  6%|▌         | 1/17 [07:14<1:55:51, 434.48s/it]

typeform/mobilebert-uncased-mnli
typeform/mobilebert-uncased-mnli #### Not exists ####

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/98.5M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/268 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cuda:0

  0%|          | 0/104 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

  1%|          | 1/104 [00:01<03:01,  1.76s/it]
  2%|▏         | 2/104 [00:02<02:13,  1.31s/it]
  3%|▎         | 3/104 [00:03<01:38,  1.03it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

  4%|▍         | 4/104 [00:03<01:21,  1.23it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

  5%|▍         | 5/104 [00:04<01:12,  1.37it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

  6%|▌         | 6/104 [00:05<01:12,  1.35it/s]
  7%|▋         | 7/104 [00:05<01:05,  1.49it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

  8%|▊         | 8/104 [00:06<00:59,  1.61it/s]
  9%|▊         | 9/104 [00:07<01:02,  1.52it/s]
 10%|▉         | 10/104 [00:07<01:09,  1.36it/s]
 11%|█         | 11/104 [00:08<01:08,  1.36it/s]
 12%|█▏        | 12/104 [00:09<01:14,  1.23it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 12%|█▎        | 13/104 [00:10<01:06,  1.37it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 13%|█▎        | 14/104 [00:11<01:13,  1.23it/s]
 14%|█▍        | 15/104 [00:11<01:09,  1.29it/s]
 15%|█▌        | 16/104 [00:12<01:04,  1.37it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 16%|█▋        | 17/104 [00:13<01:06,  1.30it/s]
 17%|█▋        | 18/104 [00:14<01:05,  1.31it/s]
 18%|█▊        | 19/104 [00:14<01:04,  1.31it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 19%|█▉        | 20/104 [00:15<01:06,  1.27it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 20%|██        | 21/104 [00:16<01:04,  1.28it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 21%|██        | 22/104 [00:17<01:03,  1.29it/s]
 22%|██▏       | 23/104 [00:18<01:10,  1.14it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 23%|██▎       | 24/104 [00:19<01:06,  1.20it/s]
 24%|██▍       | 25/104 [00:20<01:10,  1.12it/s]
 25%|██▌       | 26/104 [00:21<01:14,  1.05it/s]
 26%|██▌       | 27/104 [00:22<01:20,  1.04s/it]
 27%|██▋       | 28/104 [00:23<01:14,  1.01it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 28%|██▊       | 29/104 [00:24<01:16,  1.01s/it]
 29%|██▉       | 30/104 [00:25<01:14,  1.00s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 30%|██▉       | 31/104 [00:26<01:12,  1.01it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 31%|███       | 32/104 [00:27<01:08,  1.05it/s]
 32%|███▏      | 33/104 [00:27<01:03,  1.11it/s]
 33%|███▎      | 34/104 [00:28<00:57,  1.22it/s]
 34%|███▎      | 35/104 [00:29<00:52,  1.32it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 35%|███▍      | 36/104 [00:30<00:55,  1.22it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 36%|███▌      | 37/104 [00:31<01:06,  1.01it/s]
 37%|███▋      | 38/104 [00:32<01:06,  1.01s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 38%|███▊      | 39/104 [00:34<01:22,  1.27s/it]
 38%|███▊      | 40/104 [00:35<01:14,  1.16s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 39%|███▉      | 41/104 [00:36<01:07,  1.07s/it]
 40%|████      | 42/104 [00:36<00:57,  1.08it/s]
 41%|████▏     | 43/104 [00:37<00:55,  1.09it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 42%|████▏     | 44/104 [00:39<01:03,  1.06s/it]Exception ignored in: <function _xla_gc_callback at 0x79a85254b4c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/jax/_src/lib/__init__.py", line 127, in _xla_gc_callback
    def _xla_gc_callback(*args):

KeyboardInterrupt:

 43%|████▎     | 45/104 [00:40<01:08,  1.16s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Exception ignored in: <function _xla_gc_callback at 0x79a85254b4c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/jax/_src/lib/__init__.py", line 127, in _xla_gc_callback
    def _xla_gc_callback(*args):

KeyboardInterrupt:

 44%|████▍     | 46/104 [00:41<01:06,  1.15s/it]Exception ignored in: <function _xla_gc_callback at 0x79a85254b4c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/jax/_src/lib/__init__.py", line 127, in _xla_gc_callback
    def _xla_gc_callback(*args):

KeyboardInterrupt:

 45%|████▌     | 47/104 [00:42<00:56,  1.00it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 46%|████▌     | 48/104 [00:42<00:50,  1.12it/s]
 47%|████▋     | 49/104 [00:43<00:50,  1.10it/s]
 48%|████▊     | 50/104 [00:45<01:01,  1.14s/it]
 49%|████▉     | 51/104 [00:47<01:19,  1.49s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 50%|█████     | 52/104 [00:49<01:13,  1.41s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 51%|█████     | 53/104 [00:49<00:59,  1.16s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

 52%|█████▏    | 54/104 [00:50<00:49,  1.01it/s]

# Validations

In [ ]:
def load_results(csv_path, softmax, positiveonly, value='ASI_score', index='model'):
    df = pd.read_csv(csv_path)
    df['model'] = df['model'].str.replace('/dt/puzis/cnalab/maor/', '')
    if df['softmax'].isna().sum() > 0:
        softmax_filter = df['softmax'].isna()
    else:
        softmax_filter = df['softmax'] == ''
    if softmax:
        df = df[df['softmax'] == str(softmax)]
    else:
        df = df[softmax_filter]
    if value != 'silhouette_score':
        pass
    else:
        df = df[df['silhouette_score'] > -1]
    if positiveonly:
        df = df[df['filter']=="positiveonly"]
    else:
        df = df[df['filter']=="unfiltered"]
    results_df = pd.pivot_table(df, values=value, index=index, columns='Q', aggfunc='mean')
    return results_df

In [ ]:
softmax_soc = ['index', 'frequency']   # keep if your SOC items use these; else set to []
positiveonly = True                    # keep whatever you use for SOC


q_path = result_path / 'soc_mnli_check1.csv'
all_filters = [softmax_soc]            # iterate the SOC softmax setup(s)

## Semantic Validation

In [ ]:
# --- Semantic Validation for SOC ---

cols = ['semantic_similarity', 'cola_score', 'silhouette_score']

results = []
for softmax_filter in all_filters:  # was [softmax_asi]
    # load_results returns wide: rows = id (e.g., model), cols = Q, values = metric
    q_res = [
        load_results(q_path, softmax=softmax_filter, positiveonly=False, value=v).mean(axis=0)
        for v in cols
    ]
    results.append(pd.concat(q_res, axis=1))

linguistic_acceptability_df = pd.concat(results, axis=0)
linguistic_acceptability_df.columns = cols

# Save with Q as a column (not just the index) and fix the filename spelling
out_path = result_path / 'linguistic_acceptability_soc.csv'
linguistic_acceptability_df.reset_index(names='Q').to_csv(out_path, index=False)

linguistic_acceptability_df

                        semantic_similarity  cola_score  silhouette_score
Q
SOCComprehensibility12             0.555768    0.780181          0.728177
SOCComprehensibility19             0.559734    0.589032          0.803514
SOCComprehensibility21             0.610296    0.713771          0.672667
SOCComprehensibility26             0.649847    0.924664          0.726532
SOCComprehensibility5              0.684450    0.959107          0.451250
SOCManageability25                 0.383288    0.773223          0.792359
SOCManageability29                 0.605033    0.729215          0.541888
SOCManageability6                  0.638795    0.929842          0.628305
SOCManageability9                  0.700033    0.949978          0.800673
SOCMeaningfulness16                0.681812    0.611487          0.720332
SOCMeaningfulness28                0.599480    0.780288          0.709051
SOCMeaningfulness4                 0.406616    0.962460          0.723419
SOCMeaningfulness8                 0.333841    0.911279          0.693720

In [ ]:
linguistic_acceptability_df.mean()

semantic_similarity    0.569923
cola_score             0.816502
silhouette_score       0.691684
dtype: float64

In [ ]:
linguistic_acceptability_df.std()

semantic_similarity    0.120752
cola_score             0.132109
silhouette_score       0.101581
dtype: float64

## Internal Consistency

In [ ]:
def get_factor_sub_features(factor, data_df):
    feature_subset = []
    for subset in factor:
        feature_subset += [c for c in data_df.columns if subset in c]
    return list(set(feature_subset))

In [ ]:
soc_factors = ['C', 'M', 'Me']

In [ ]:
value='mean_score'

results = []
for softmax_filter in [softmax_soc]:
    results.append(load_results(q_path,softmax=softmax_filter,positiveonly=positiveonly, value=value))

data_df = pd.concat(results, axis=1)

print('Cronbach Alpha:')
for subset in soc_factors:
    feature_subset = [c for c in data_df.columns if subset in c]
    alpha = pg.cronbach_alpha(data=data_df[feature_subset])
    print(f'{subset}, Alpha:, {alpha}')

asi_feature_subset = get_factor_sub_features(soc_factors, data_df)
alpha = pg.cronbach_alpha(data=data_df[asi_feature_subset])
print(f'SOC, Alpha:, {alpha}')

Cronbach Alpha:
C, Alpha:, (np.float64(0.813303866708712), array([0.62 , 0.933]))
M, Alpha:, (np.float64(0.7771542401912809), array([0.531, 0.921]))
Me, Alpha:, (np.float64(0.9292112973361784), array([0.835, 0.976]))
SOC, Alpha:, (np.float64(0.813303866708712), array([0.62 , 0.933]))

In [ ]:

soc_scores = pd.DataFrame(index=data_df.index)
for f in soc_factors:
    cols = get_factor_sub_features([f], data_df)
    if len(cols) > 0:
        soc_scores[f] = data_df[cols].mean(axis=1, skipna=True)

# Optional overall SOC score
soc_all_cols = get_factor_sub_features(soc_factors, data_df)
if len(soc_all_cols) > 0:
    soc_scores['SOC'] = data_df[soc_all_cols].mean(axis=1, skipna=True)

# Drop completely empty columns (if any)
soc_scores = soc_scores.dropna(axis=1, how='all')

# 2) Pearson correlation matrix (no p-values)
pearson_mat = soc_scores.corr(method='pearson')
print("SOC Pearson correlation matrix:")
print(pearson_mat)

# 3) Pearson with p-values (Pingouin)
if soc_scores.shape[1] >= 2 and soc_scores.shape[0] >= 3:
    pearson_with_p = pg.rcorr(soc_scores, method='pearson')  # returns r and p
    print("\nSOC Pearson correlations (Pingouin r & p):")
    print(pearson_with_p)
else:
    print("\nNot enough data for pg.rcorr (need ≥2 variables and ≥3 rows).")

SOC Pearson correlation matrix:
            C         M        Me       SOC
C    1.000000  0.969243  0.788724  1.000000
M    0.969243  1.000000  0.858495  0.969243
Me   0.788724  0.858495  1.000000  0.788724
SOC  1.000000  0.969243  0.788724  1.000000

SOC Pearson correlations (Pingouin r & p):
         C      M     Me  SOC
C        -    ***     **  ***
M    0.969      -    ***  ***
Me   0.789  0.858      -   **
SOC    1.0  0.969  0.789    -