In [13]:
from qpsychometric.questionnaire_validator import QuestionnaireValidator
from qpsychometric.mental_health.generalized_anxiety_disorder import gad_questionnaire

In [14]:
# Import gad questions
gad_qmnli_df = gad_questionnaire['QMNLI']
gad_questions = gad_qmnli_df.get_questions()

gad_factors = list(set([q()._descriptor['Factor'] for q in gad_questions]))

In [15]:
# Create validator instance
validator = QuestionnaireValidator(
    questionnaire_name="gad",
    questions=gad_questions,
    factors=gad_factors,
    result_path="results/",
    update=False,
)

results = validator.run_validation()

Loading validation models...

/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py:560: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Models loaded successfully.
Splitting 7 questions...
Generated 56 question variants.
Initialized gad Validator:
  - Questions: 7
  - Factors: ['GAD7']
  - Scales: ['frequency']
  - Index: ['index']
  - Device: 0
  - Result path: results

======================================================================
Running Complete Validation for gad Questionnaire
======================================================================

Running model evaluation with 56 question variants...

Evaluating models:   0%|          | 0/17 [00:00<?, ?it/s]

Evaluating model: typeform/distilbert-base-uncased-mnli
skip typeform/distilbert-base-uncased-mnli GAD7GAD71
skip typeform/distilbert-base-uncased-mnli GAD7GAD71
skip typeform/distilbert-base-uncased-mnli GAD7GAD71
skip typeform/distilbert-base-uncased-mnli GAD7GAD71
skip typeform/distilbert-base-uncased-mnli GAD7GAD71
skip typeform/distilbert-base-uncased-mnli GAD7GAD71
skip typeform/distilbert-base-uncased-mnli GAD7GAD71
skip typeform/distilbert-base-uncased-mnli GAD7GAD71
skip typeform/distilbert-base-uncased-mnli GAD7GAD72
skip typeform/distilbert-base-uncased-mnli GAD7GAD72
skip typeform/distilbert-base-uncased-mnli GAD7GAD72
skip typeform/distilbert-base-uncased-mnli GAD7GAD72
skip typeform/distilbert-base-uncased-mnli GAD7GAD72
skip typeform/distilbert-base-uncased-mnli GAD7GAD72
skip typeform/distilbert-base-uncased-mnli GAD7GAD72
skip typeform/distilbert-base-uncased-mnli GAD7GAD72
skip typeform/distilbert-base-uncased-mnli GAD7GAD73
skip typeform/distilbert-base-uncased-mnli GAD7GAD73
skip typeform/distilbert-base-uncased-mnli GAD7GAD73
skip typeform/distilbert-base-uncased-mnli GAD7GAD73
skip typeform/distilbert-base-uncased-mnli GAD7GAD73
skip typeform/distilbert-base-uncased-mnli GAD7GAD73
skip typeform/distilbert-base-uncased-mnli GAD7GAD73
skip typeform/distilbert-base-uncased-mnli GAD7GAD73
skip typeform/distilbert-base-uncased-mnli GAD7GAD74
skip typeform/distilbert-base-uncased-mnli GAD7GAD74
skip typeform/distilbert-base-uncased-mnli GAD7GAD74
skip typeform/distilbert-base-uncased-mnli GAD7GAD74
skip typeform/distilbert-base-uncased-mnli GAD7GAD74
skip typeform/distilbert-base-uncased-mnli GAD7GAD74
skip typeform/distilbert-base-uncased-mnli GAD7GAD74
skip typeform/distilbert-base-uncased-mnli GAD7GAD74
skip typeform/distilbert-base-uncased-mnli GAD7GAD75
skip typeform/distilbert-base-uncased-mnli GAD7GAD75
skip typeform/distilbert-base-uncased-mnli GAD7GAD75
skip typeform/distilbert-base-uncased-mnli GAD7GAD75
skip typeform/distilbert-base-uncased-mnli GAD7GAD75
skip typeform/distilbert-base-uncased-mnli GAD7GAD75
skip typeform/distilbert-base-uncased-mnli GAD7GAD75
skip typeform/distilbert-base-uncased-mnli GAD7GAD75
skip typeform/distilbert-base-uncased-mnli GAD7GAD76
skip typeform/distilbert-base-uncased-mnli GAD7GAD76
skip typeform/distilbert-base-uncased-mnli GAD7GAD76
skip typeform/distilbert-base-uncased-mnli GAD7GAD76
skip typeform/distilbert-base-uncased-mnli GAD7GAD76
skip typeform/distilbert-base-uncased-mnli GAD7GAD76
skip typeform/distilbert-base-uncased-mnli GAD7GAD76
skip typeform/distilbert-base-uncased-mnli GAD7GAD76
skip typeform/distilbert-base-uncased-mnli GAD7GAD77
skip typeform/distilbert-base-uncased-mnli GAD7GAD77
skip typeform/distilbert-base-uncased-mnli GAD7GAD77
skip typeform/distilbert-base-uncased-mnli GAD7GAD77
skip typeform/distilbert-base-uncased-mnli GAD7GAD77
skip typeform/distilbert-base-uncased-mnli GAD7GAD77
skip typeform/distilbert-base-uncased-mnli GAD7GAD77
skip typeform/distilbert-base-uncased-mnli GAD7GAD77
All questions already evaluated for typeform/distilbert-base-uncased-mnli, skipping...

Evaluating model: typeform/mobilebert-uncased-mnli
skip typeform/mobilebert-uncased-mnli GAD7GAD71
skip typeform/mobilebert-uncased-mnli GAD7GAD71
skip typeform/mobilebert-uncased-mnli GAD7GAD71
skip typeform/mobilebert-uncased-mnli GAD7GAD71
skip typeform/mobilebert-uncased-mnli GAD7GAD71
skip typeform/mobilebert-uncased-mnli GAD7GAD71
skip typeform/mobilebert-uncased-mnli GAD7GAD71
skip typeform/mobilebert-uncased-mnli GAD7GAD71
skip typeform/mobilebert-uncased-mnli GAD7GAD72
skip typeform/mobilebert-uncased-mnli GAD7GAD72
skip typeform/mobilebert-uncased-mnli GAD7GAD72
skip typeform/mobilebert-uncased-mnli GAD7GAD72
skip typeform/mobilebert-uncased-mnli GAD7GAD72
skip typeform/mobilebert-uncased-mnli GAD7GAD72
skip typeform/mobilebert-uncased-mnli GAD7GAD72
skip typeform/mobilebert-uncased-mnli GAD7GAD72
skip typeform/mobilebert-uncased-mnli GAD7GAD73
skip typeform/mobilebert-uncased-mnli GAD7GAD73
skip typeform/mobilebert-uncased-mnli GAD7GAD73
skip typeform/mobilebert-uncased-mnli GAD7GAD73
skip typeform/mobilebert-uncased-mnli GAD7GAD73
skip typeform/mobilebert-uncased-mnli GAD7GAD73
skip typeform/mobilebert-uncased-mnli GAD7GAD73
skip typeform/mobilebert-uncased-mnli GAD7GAD73
skip typeform/mobilebert-uncased-mnli GAD7GAD74
skip typeform/mobilebert-uncased-mnli GAD7GAD74
skip typeform/mobilebert-uncased-mnli GAD7GAD74
skip typeform/mobilebert-uncased-mnli GAD7GAD74
skip typeform/mobilebert-uncased-mnli GAD7GAD74
skip typeform/mobilebert-uncased-mnli GAD7GAD74
skip typeform/mobilebert-uncased-mnli GAD7GAD74
skip typeform/mobilebert-uncased-mnli GAD7GAD74
skip typeform/mobilebert-uncased-mnli GAD7GAD75
skip typeform/mobilebert-uncased-mnli GAD7GAD75
skip typeform/mobilebert-uncased-mnli GAD7GAD75
skip typeform/mobilebert-uncased-mnli GAD7GAD75
skip typeform/mobilebert-uncased-mnli GAD7GAD75
skip typeform/mobilebert-uncased-mnli GAD7GAD75
skip typeform/mobilebert-uncased-mnli GAD7GAD75
skip typeform/mobilebert-uncased-mnli GAD7GAD75
skip typeform/mobilebert-uncased-mnli GAD7GAD76
skip typeform/mobilebert-uncased-mnli GAD7GAD76
skip typeform/mobilebert-uncased-mnli GAD7GAD76
skip typeform/mobilebert-uncased-mnli GAD7GAD76
skip typeform/mobilebert-uncased-mnli GAD7GAD76
skip typeform/mobilebert-uncased-mnli GAD7GAD76
skip typeform/mobilebert-uncased-mnli GAD7GAD76
skip typeform/mobilebert-uncased-mnli GAD7GAD76
skip typeform/mobilebert-uncased-mnli GAD7GAD77
skip typeform/mobilebert-uncased-mnli GAD7GAD77
skip typeform/mobilebert-uncased-mnli GAD7GAD77
skip typeform/mobilebert-uncased-mnli GAD7GAD77
skip typeform/mobilebert-uncased-mnli GAD7GAD77
skip typeform/mobilebert-uncased-mnli GAD7GAD77
skip typeform/mobilebert-uncased-mnli GAD7GAD77
skip typeform/mobilebert-uncased-mnli GAD7GAD77
All questions already evaluated for typeform/mobilebert-uncased-mnli, skipping...

Evaluating model: cross-encoder/nli-roberta-base

Evaluating models:  18%|█▊        | 3/17 [00:00<00:01,  8.86it/s]

Error evaluating cross-encoder/nli-roberta-base: data did not match any variant of untagged enum ModelWrapper at line 250356 column 3

Evaluating model: cross-encoder/nli-deberta-base
skip cross-encoder/nli-deberta-base GAD7GAD71
skip cross-encoder/nli-deberta-base GAD7GAD71
skip cross-encoder/nli-deberta-base GAD7GAD71
skip cross-encoder/nli-deberta-base GAD7GAD71
skip cross-encoder/nli-deberta-base GAD7GAD71
skip cross-encoder/nli-deberta-base GAD7GAD71
skip cross-encoder/nli-deberta-base GAD7GAD71
skip cross-encoder/nli-deberta-base GAD7GAD71
skip cross-encoder/nli-deberta-base GAD7GAD72
skip cross-encoder/nli-deberta-base GAD7GAD72
skip cross-encoder/nli-deberta-base GAD7GAD72
skip cross-encoder/nli-deberta-base GAD7GAD72
skip cross-encoder/nli-deberta-base GAD7GAD72
skip cross-encoder/nli-deberta-base GAD7GAD72
skip cross-encoder/nli-deberta-base GAD7GAD72
skip cross-encoder/nli-deberta-base GAD7GAD72
skip cross-encoder/nli-deberta-base GAD7GAD73
skip cross-encoder/nli-deberta-base GAD7GAD73
skip cross-encoder/nli-deberta-base GAD7GAD73
skip cross-encoder/nli-deberta-base GAD7GAD73
skip cross-encoder/nli-deberta-base GAD7GAD73
skip cross-encoder/nli-deberta-base GAD7GAD73
skip cross-encoder/nli-deberta-base GAD7GAD73
skip cross-encoder/nli-deberta-base GAD7GAD73
skip cross-encoder/nli-deberta-base GAD7GAD74
skip cross-encoder/nli-deberta-base GAD7GAD74
skip cross-encoder/nli-deberta-base GAD7GAD74
skip cross-encoder/nli-deberta-base GAD7GAD74
skip cross-encoder/nli-deberta-base GAD7GAD74
skip cross-encoder/nli-deberta-base GAD7GAD74
skip cross-encoder/nli-deberta-base GAD7GAD74
skip cross-encoder/nli-deberta-base GAD7GAD74
skip cross-encoder/nli-deberta-base GAD7GAD75
skip cross-encoder/nli-deberta-base GAD7GAD75
skip cross-encoder/nli-deberta-base GAD7GAD75
skip cross-encoder/nli-deberta-base GAD7GAD75
skip cross-encoder/nli-deberta-base GAD7GAD75
skip cross-encoder/nli-deberta-base GAD7GAD75
skip cross-encoder/nli-deberta-base GAD7GAD75
skip cross-encoder/nli-deberta-base GAD7GAD75
skip cross-encoder/nli-deberta-base GAD7GAD76
skip cross-encoder/nli-deberta-base GAD7GAD76
skip cross-encoder/nli-deberta-base GAD7GAD76
skip cross-encoder/nli-deberta-base GAD7GAD76
skip cross-encoder/nli-deberta-base GAD7GAD76
skip cross-encoder/nli-deberta-base GAD7GAD76
skip cross-encoder/nli-deberta-base GAD7GAD76
skip cross-encoder/nli-deberta-base GAD7GAD76
skip cross-encoder/nli-deberta-base GAD7GAD77
skip cross-encoder/nli-deberta-base GAD7GAD77
skip cross-encoder/nli-deberta-base GAD7GAD77
skip cross-encoder/nli-deberta-base GAD7GAD77
skip cross-encoder/nli-deberta-base GAD7GAD77
skip cross-encoder/nli-deberta-base GAD7GAD77
skip cross-encoder/nli-deberta-base GAD7GAD77
skip cross-encoder/nli-deberta-base GAD7GAD77
All questions already evaluated for cross-encoder/nli-deberta-base, skipping...

Evaluating model: cross-encoder/nli-distilroberta-base

Evaluating models:  29%|██▉       | 5/17 [00:00<00:01,  6.52it/s]

Error evaluating cross-encoder/nli-distilroberta-base: data did not match any variant of untagged enum ModelWrapper at line 250356 column 3

Evaluating model: cross-encoder/nli-MiniLM2-L6-H768
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD71
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD71
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD71
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD71
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD71
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD71
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD71
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD71
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD72
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD72
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD72
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD72
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD72
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD72
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD72
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD72
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD73
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD73
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD73
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD73
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD73
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD73
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD73
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD73
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD74
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD74
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD74
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD74
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD74
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD74
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD74
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD74
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD75
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD75
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD75
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD75
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD75
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD75
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD75
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD75
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD76
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD76
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD76
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD76
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD76
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD76
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD76
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD76
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD77
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD77
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD77
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD77
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD77
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD77
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD77
skip cross-encoder/nli-MiniLM2-L6-H768 GAD7GAD77
All questions already evaluated for cross-encoder/nli-MiniLM2-L6-H768, skipping...

Evaluating model: navteca/bart-large-mnli
skip navteca/bart-large-mnli GAD7GAD71
skip navteca/bart-large-mnli GAD7GAD71
skip navteca/bart-large-mnli GAD7GAD71
skip navteca/bart-large-mnli GAD7GAD71
skip navteca/bart-large-mnli GAD7GAD71
skip navteca/bart-large-mnli GAD7GAD71
skip navteca/bart-large-mnli GAD7GAD71
skip navteca/bart-large-mnli GAD7GAD71
skip navteca/bart-large-mnli GAD7GAD72
skip navteca/bart-large-mnli GAD7GAD72
skip navteca/bart-large-mnli GAD7GAD72
skip navteca/bart-large-mnli GAD7GAD72
skip navteca/bart-large-mnli GAD7GAD72
skip navteca/bart-large-mnli GAD7GAD72
skip navteca/bart-large-mnli GAD7GAD72
skip navteca/bart-large-mnli GAD7GAD72
skip navteca/bart-large-mnli GAD7GAD73
skip navteca/bart-large-mnli GAD7GAD73
skip navteca/bart-large-mnli GAD7GAD73
skip navteca/bart-large-mnli GAD7GAD73
skip navteca/bart-large-mnli GAD7GAD73
skip navteca/bart-large-mnli GAD7GAD73
skip navteca/bart-large-mnli GAD7GAD73
skip navteca/bart-large-mnli GAD7GAD73
skip navteca/bart-large-mnli GAD7GAD74
skip navteca/bart-large-mnli GAD7GAD74
skip navteca/bart-large-mnli GAD7GAD74
skip navteca/bart-large-mnli GAD7GAD74
skip navteca/bart-large-mnli GAD7GAD74
skip navteca/bart-large-mnli GAD7GAD74
skip navteca/bart-large-mnli GAD7GAD74
skip navteca/bart-large-mnli GAD7GAD74
skip navteca/bart-large-mnli GAD7GAD75
skip navteca/bart-large-mnli GAD7GAD75
skip navteca/bart-large-mnli GAD7GAD75
skip navteca/bart-large-mnli GAD7GAD75
skip navteca/bart-large-mnli GAD7GAD75
skip navteca/bart-large-mnli GAD7GAD75
skip navteca/bart-large-mnli GAD7GAD75
skip navteca/bart-large-mnli GAD7GAD75
skip navteca/bart-large-mnli GAD7GAD76
skip navteca/bart-large-mnli GAD7GAD76
skip navteca/bart-large-mnli GAD7GAD76
skip navteca/bart-large-mnli GAD7GAD76
skip navteca/bart-large-mnli GAD7GAD76
skip navteca/bart-large-mnli GAD7GAD76
skip navteca/bart-large-mnli GAD7GAD76
skip navteca/bart-large-mnli GAD7GAD76
skip navteca/bart-large-mnli GAD7GAD77
skip navteca/bart-large-mnli GAD7GAD77
skip navteca/bart-large-mnli GAD7GAD77
skip navteca/bart-large-mnli GAD7GAD77
skip navteca/bart-large-mnli GAD7GAD77
skip navteca/bart-large-mnli GAD7GAD77
skip navteca/bart-large-mnli GAD7GAD77
skip navteca/bart-large-mnli GAD7GAD77
All questions already evaluated for navteca/bart-large-mnli, skipping...

Evaluating model: digitalepidemiologylab/covid-twitter-bert-v2-mnli
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD71
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD71
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD71
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD71
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD71
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD71
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD71
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD71
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD72
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD72
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD72
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD72
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD72
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD72
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD72
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD72
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD73
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD73
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD73
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD73
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD73
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD73
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD73
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD73
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD74
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD74
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD74
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD74
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD74
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD74
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD74
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD74
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD75
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD75
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD75
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD75
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD75
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD75
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD75
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD75
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD76
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD76
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD76
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD76
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD76
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD76
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD76
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD76
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD77
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD77
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD77
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD77
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD77
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD77
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD77
skip digitalepidemiologylab/covid-twitter-bert-v2-mnli GAD7GAD77
All questions already evaluated for digitalepidemiologylab/covid-twitter-bert-v2-mnli, skipping...

Evaluating model: joeddav/bart-large-mnli-yahoo-answers
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD71
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD71
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD71
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD71
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD71
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD71
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD71
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD71
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD72
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD72
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD72
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD72
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD72
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD72
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD72
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD72
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD73
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD73
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD73
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD73
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD73
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD73
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD73
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD73
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD74
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD74
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD74
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD74
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD74
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD74
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD74
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD74
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD75
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD75
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD75
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD75
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD75
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD75
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD75
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD75
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD76
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD76
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD76
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD76
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD76
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD76
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD76
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD76
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD77
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD77
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD77
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD77
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD77
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD77
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD77
skip joeddav/bart-large-mnli-yahoo-answers GAD7GAD77
All questions already evaluated for joeddav/bart-large-mnli-yahoo-answers, skipping...

Evaluating model: Narsil/deberta-large-mnli-zero-cls
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD71
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD71
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD71
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD71
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD71
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD71
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD71
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD71
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD72
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD72
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD72
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD72
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD72
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD72
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD72
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD72
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD73
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD73
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD73
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD73
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD73
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD73
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD73
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD73
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD74
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD74
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD74
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD74
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD74
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD74
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD74
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD74
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD75
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD75
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD75
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD75
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD75
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD75
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD75
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD75
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD76
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD76
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD76
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD76
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD76
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD76
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD76
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD76
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD77
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD77
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD77
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD77
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD77
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD77
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD77
skip Narsil/deberta-large-mnli-zero-cls GAD7GAD77
All questions already evaluated for Narsil/deberta-large-mnli-zero-cls, skipping...

Evaluating model: microsoft/deberta-large-mnli
skip microsoft/deberta-large-mnli GAD7GAD71
skip microsoft/deberta-large-mnli GAD7GAD71
skip microsoft/deberta-large-mnli GAD7GAD71
skip microsoft/deberta-large-mnli GAD7GAD71
skip microsoft/deberta-large-mnli GAD7GAD71
skip microsoft/deberta-large-mnli GAD7GAD71
skip microsoft/deberta-large-mnli GAD7GAD71
skip microsoft/deberta-large-mnli GAD7GAD71
skip microsoft/deberta-large-mnli GAD7GAD72
skip microsoft/deberta-large-mnli GAD7GAD72
skip microsoft/deberta-large-mnli GAD7GAD72
skip microsoft/deberta-large-mnli GAD7GAD72
skip microsoft/deberta-large-mnli GAD7GAD72
skip microsoft/deberta-large-mnli GAD7GAD72
skip microsoft/deberta-large-mnli GAD7GAD72
skip microsoft/deberta-large-mnli GAD7GAD72
skip microsoft/deberta-large-mnli GAD7GAD73
skip microsoft/deberta-large-mnli GAD7GAD73
skip microsoft/deberta-large-mnli GAD7GAD73
skip microsoft/deberta-large-mnli GAD7GAD73
skip microsoft/deberta-large-mnli GAD7GAD73
skip microsoft/deberta-large-mnli GAD7GAD73
skip microsoft/deberta-large-mnli GAD7GAD73
skip microsoft/deberta-large-mnli GAD7GAD73
skip microsoft/deberta-large-mnli GAD7GAD74
skip microsoft/deberta-large-mnli GAD7GAD74
skip microsoft/deberta-large-mnli GAD7GAD74
skip microsoft/deberta-large-mnli GAD7GAD74
skip microsoft/deberta-large-mnli GAD7GAD74
skip microsoft/deberta-large-mnli GAD7GAD74
skip microsoft/deberta-large-mnli GAD7GAD74
skip microsoft/deberta-large-mnli GAD7GAD74
skip microsoft/deberta-large-mnli GAD7GAD75
skip microsoft/deberta-large-mnli GAD7GAD75
skip microsoft/deberta-large-mnli GAD7GAD75
skip microsoft/deberta-large-mnli GAD7GAD75
skip microsoft/deberta-large-mnli GAD7GAD75
skip microsoft/deberta-large-mnli GAD7GAD75
skip microsoft/deberta-large-mnli GAD7GAD75
skip microsoft/deberta-large-mnli GAD7GAD75
skip microsoft/deberta-large-mnli GAD7GAD76
skip microsoft/deberta-large-mnli GAD7GAD76
skip microsoft/deberta-large-mnli GAD7GAD76
skip microsoft/deberta-large-mnli GAD7GAD76
skip microsoft/deberta-large-mnli GAD7GAD76
skip microsoft/deberta-large-mnli GAD7GAD76
skip microsoft/deberta-large-mnli GAD7GAD76
skip microsoft/deberta-large-mnli GAD7GAD76
skip microsoft/deberta-large-mnli GAD7GAD77
skip microsoft/deberta-large-mnli GAD7GAD77
skip microsoft/deberta-large-mnli GAD7GAD77
skip microsoft/deberta-large-mnli GAD7GAD77
skip microsoft/deberta-large-mnli GAD7GAD77
skip microsoft/deberta-large-mnli GAD7GAD77
skip microsoft/deberta-large-mnli GAD7GAD77
skip microsoft/deberta-large-mnli GAD7GAD77
All questions already evaluated for microsoft/deberta-large-mnli, skipping...

Evaluating model: microsoft/deberta-base-mnli
skip microsoft/deberta-base-mnli GAD7GAD71
skip microsoft/deberta-base-mnli GAD7GAD71
skip microsoft/deberta-base-mnli GAD7GAD71
skip microsoft/deberta-base-mnli GAD7GAD71
skip microsoft/deberta-base-mnli GAD7GAD71
skip microsoft/deberta-base-mnli GAD7GAD71
skip microsoft/deberta-base-mnli GAD7GAD71
skip microsoft/deberta-base-mnli GAD7GAD71
skip microsoft/deberta-base-mnli GAD7GAD72
skip microsoft/deberta-base-mnli GAD7GAD72
skip microsoft/deberta-base-mnli GAD7GAD72
skip microsoft/deberta-base-mnli GAD7GAD72
skip microsoft/deberta-base-mnli GAD7GAD72
skip microsoft/deberta-base-mnli GAD7GAD72
skip microsoft/deberta-base-mnli GAD7GAD72
skip microsoft/deberta-base-mnli GAD7GAD72
skip microsoft/deberta-base-mnli GAD7GAD73
skip microsoft/deberta-base-mnli GAD7GAD73
skip microsoft/deberta-base-mnli GAD7GAD73
skip microsoft/deberta-base-mnli GAD7GAD73
skip microsoft/deberta-base-mnli GAD7GAD73
skip microsoft/deberta-base-mnli GAD7GAD73
skip microsoft/deberta-base-mnli GAD7GAD73
skip microsoft/deberta-base-mnli GAD7GAD73
skip microsoft/deberta-base-mnli GAD7GAD74
skip microsoft/deberta-base-mnli GAD7GAD74
skip microsoft/deberta-base-mnli GAD7GAD74
skip microsoft/deberta-base-mnli GAD7GAD74
skip microsoft/deberta-base-mnli GAD7GAD74
skip microsoft/deberta-base-mnli GAD7GAD74
skip microsoft/deberta-base-mnli GAD7GAD74
skip microsoft/deberta-base-mnli GAD7GAD74
skip microsoft/deberta-base-mnli GAD7GAD75
skip microsoft/deberta-base-mnli GAD7GAD75
skip microsoft/deberta-base-mnli GAD7GAD75
skip microsoft/deberta-base-mnli GAD7GAD75
skip microsoft/deberta-base-mnli GAD7GAD75
skip microsoft/deberta-base-mnli GAD7GAD75
skip microsoft/deberta-base-mnli GAD7GAD75
skip microsoft/deberta-base-mnli GAD7GAD75
skip microsoft/deberta-base-mnli GAD7GAD76
skip microsoft/deberta-base-mnli GAD7GAD76
skip microsoft/deberta-base-mnli GAD7GAD76
skip microsoft/deberta-base-mnli GAD7GAD76
skip microsoft/deberta-base-mnli GAD7GAD76
skip microsoft/deberta-base-mnli GAD7GAD76
skip microsoft/deberta-base-mnli GAD7GAD76
skip microsoft/deberta-base-mnli GAD7GAD76
skip microsoft/deberta-base-mnli GAD7GAD77
skip microsoft/deberta-base-mnli GAD7GAD77

Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.
Processing questions:   0%|          | 0/56 [00:00<?, ?it/s]
Evaluating models:  76%|███████▋  | 13/17 [00:01<00:00, 10.86it/s]

Error evaluating Alireza1044/albert-base-v2-mnli: The entailment id of the MNLI model is not determine.  please update label name to {"CONTRADICTION", "ENTAILMENT", "NEUTRAL"} in self.model.config

Evaluating model: yoshitomo-matsubara/bert-large-uncased-mnli

Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.
Processing questions:   0%|          | 0/56 [00:00<?, ?it/s]

Error evaluating yoshitomo-matsubara/bert-large-uncased-mnli: The entailment id of the MNLI model is not determine.  please update label name to {"CONTRADICTION", "ENTAILMENT", "NEUTRAL"} in self.model.config

Evaluating model: yoshitomo-matsubara/bert-base-uncased-mnli

Evaluating models:  76%|███████▋  | 13/17 [00:13<00:00, 10.86it/s]Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.
Processing questions:   0%|          | 0/56 [00:00<?, ?it/s]
Evaluating models:  88%|████████▊ | 15/17 [00:18<00:03,  1.91s/it]

Error evaluating yoshitomo-matsubara/bert-base-uncased-mnli: The entailment id of the MNLI model is not determine.  please update label name to {"CONTRADICTION", "ENTAILMENT", "NEUTRAL"} in self.model.config

Evaluating model: yoshitomo-matsubara/bert-base-uncased-mnli_from_bert-large-uncased-mnli

Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.
Processing questions:   0%|          | 0/56 [00:00<?, ?it/s]
Evaluating models: 100%|██████████| 17/17 [00:25<00:00,  1.50s/it]

Error evaluating yoshitomo-matsubara/bert-base-uncased-mnli_from_bert-large-uncased-mnli: The entailment id of the MNLI model is not determine.  please update label name to {"CONTRADICTION", "ENTAILMENT", "NEUTRAL"} in self.model.config

Evaluating model: valhalla/distilbart-mnli-12-6
skip valhalla/distilbart-mnli-12-6 GAD7GAD71
skip valhalla/distilbart-mnli-12-6 GAD7GAD71
skip valhalla/distilbart-mnli-12-6 GAD7GAD71
skip valhalla/distilbart-mnli-12-6 GAD7GAD71
skip valhalla/distilbart-mnli-12-6 GAD7GAD71
skip valhalla/distilbart-mnli-12-6 GAD7GAD71
skip valhalla/distilbart-mnli-12-6 GAD7GAD71
skip valhalla/distilbart-mnli-12-6 GAD7GAD71
skip valhalla/distilbart-mnli-12-6 GAD7GAD72
skip valhalla/distilbart-mnli-12-6 GAD7GAD72
skip valhalla/distilbart-mnli-12-6 GAD7GAD72
skip valhalla/distilbart-mnli-12-6 GAD7GAD72
skip valhalla/distilbart-mnli-12-6 GAD7GAD72
skip valhalla/distilbart-mnli-12-6 GAD7GAD72
skip valhalla/distilbart-mnli-12-6 GAD7GAD72
skip valhalla/distilbart-mnli-12-6 GAD7GAD72
skip valhalla/distilbart-mnli-12-6 GAD7GAD73
skip valhalla/distilbart-mnli-12-6 GAD7GAD73
skip valhalla/distilbart-mnli-12-6 GAD7GAD73
skip valhalla/distilbart-mnli-12-6 GAD7GAD73
skip valhalla/distilbart-mnli-12-6 GAD7GAD73
skip valhalla/distilbart-mnli-12-6 GAD7GAD73
skip valhalla/distilbart-mnli-12-6 GAD7GAD73
skip valhalla/distilbart-mnli-12-6 GAD7GAD73
skip valhalla/distilbart-mnli-12-6 GAD7GAD74
skip valhalla/distilbart-mnli-12-6 GAD7GAD74
skip valhalla/distilbart-mnli-12-6 GAD7GAD74
skip valhalla/distilbart-mnli-12-6 GAD7GAD74
skip valhalla/distilbart-mnli-12-6 GAD7GAD74
skip valhalla/distilbart-mnli-12-6 GAD7GAD74
skip valhalla/distilbart-mnli-12-6 GAD7GAD74
skip valhalla/distilbart-mnli-12-6 GAD7GAD74
skip valhalla/distilbart-mnli-12-6 GAD7GAD75
skip valhalla/distilbart-mnli-12-6 GAD7GAD75
skip valhalla/distilbart-mnli-12-6 GAD7GAD75
skip valhalla/distilbart-mnli-12-6 GAD7GAD75
skip valhalla/distilbart-mnli-12-6 GAD7GAD75
skip valhalla/distilbart-mnli-12-6 GAD7GAD75
skip valhalla/distilbart-mnli-12-6 GAD7GAD75
skip valhalla/distilbart-mnli-12-6 GAD7GAD75
skip valhalla/distilbart-mnli-12-6 GAD7GAD76
skip valhalla/distilbart-mnli-12-6 GAD7GAD76
skip valhalla/distilbart-mnli-12-6 GAD7GAD76
skip valhalla/distilbart-mnli-12-6 GAD7GAD76
skip valhalla/distilbart-mnli-12-6 GAD7GAD76
skip valhalla/distilbart-mnli-12-6 GAD7GAD76
skip valhalla/distilbart-mnli-12-6 GAD7GAD76
skip valhalla/distilbart-mnli-12-6 GAD7GAD76
skip valhalla/distilbart-mnli-12-6 GAD7GAD77
skip valhalla/distilbart-mnli-12-6 GAD7GAD77
skip valhalla/distilbart-mnli-12-6 GAD7GAD77
skip valhalla/distilbart-mnli-12-6 GAD7GAD77
skip valhalla/distilbart-mnli-12-6 GAD7GAD77
skip valhalla/distilbart-mnli-12-6 GAD7GAD77
skip valhalla/distilbart-mnli-12-6 GAD7GAD77
skip valhalla/distilbart-mnli-12-6 GAD7GAD77
All questions already evaluated for valhalla/distilbart-mnli-12-6, skipping...

✓ Model evaluation complete. Results saved to: results/gad_mnli_results.csv

======================================================================
Calculating Content Validity Metrics
======================================================================

✓ Content validity metrics saved to: results/linguistic_acceptability.csv

Content Validity Results:
           semantic_similarity  cola_score  silhouette_score
Q
GAD7GAD73             0.625611    0.834006          0.630896
GAD7GAD75             0.620217    0.869899          0.677813
GAD7GAD72             0.461051    0.879951          0.707341
GAD7GAD71             0.656900    0.936055          0.726579
GAD7GAD77             0.523310    0.933155          0.751356
GAD7GAD76             0.611590    0.852854          0.760295
GAD7GAD74             0.734749    0.924410          0.810173

======================================================================
Calculating Internal Consistency (Cronbach's Alpha)
======================================================================

Cronbach Alpha:
GAD7: (0.9557867909490871, array([0.9  , 0.986]))

gad Overall: (0.9557867909490871, array([0.9  , 0.986]))

======================================================================
Calculating Factor Correlations
======================================================================

✓ Factor correlations (spearman):
     GAD7  gad
GAD7    -  ***
gad   1.0    -

======================================================================
Validation Complete!
======================================================================
Results saved in: results

In [16]:
results.keys()

dict_keys(['results_csv', 'content_validity', 'cronbach_alpha', 'correlations'])

In [17]:
results['results_csv']

PosixPath('results/gad_mnli_results.csv')

In [18]:
results['content_validity']

           semantic_similarity  cola_score  silhouette_score
Q
GAD7GAD73             0.625611    0.834006          0.630896
GAD7GAD75             0.620217    0.869899          0.677813
GAD7GAD72             0.461051    0.879951          0.707341
GAD7GAD71             0.656900    0.936055          0.726579
GAD7GAD77             0.523310    0.933155          0.751356
GAD7GAD76             0.611590    0.852854          0.760295
GAD7GAD74             0.734749    0.924410          0.810173

In [19]:
results['cronbach_alpha']["overall"]

(0.9557867909490871, array([0.9  , 0.986]))

In [20]:
results['cronbach_alpha']["factors"]

{'GAD7': (0.9557867909490871, array([0.9  , 0.986]))}

In [21]:
results['correlations']

     GAD7  gad
GAD7    -  ***
gad   1.0    -