In [1]:
from qpsychometric.questionnaire_validator import QuestionnaireValidator
from qpsychometric.mental_health.sense_of_coherence import soc_questionnaire

/home/amonfadi/.local/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/utils/generic.py:481: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/utils/generic.py:338: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/utils/generic.py:338: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(

In [2]:
# Import soc questions
soc_qmnli_df = soc_questionnaire['QMNLI']
soc_questions = soc_qmnli_df.get_questions()

soc_factors = list(set([q()._descriptor['Factor'] for q in soc_questions]))

In [3]:
soc_questions

[qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ4,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ5,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ6,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ8,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ9,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ12,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ16,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ19,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ21,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ25,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ26,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ28,
 qpsychometric.mental_health.sense_of_coherence.soc_qmnli.SOCQ29]

In [4]:
# Create validator instance
validator = QuestionnaireValidator(
    questionnaire_name="soc",
    questions=[soc_questions[-4],soc_questions[3]],
    factors=soc_factors,
    result_path="results/",
    update=True
)

Loading validation models...

/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/utils/generic.py:338: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py:560: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Models loaded successfully.
Splitting 2 questions...
Generated 16 question variants.
Initialized soc Validator:
  - Questions: 2
  - Factors: ['Comprehensibility', 'Manageability', 'Meaningfulness']
  - Scales: ['frequency']
  - Index: ['index']
  - Device: 0
  - Result path: results

In [5]:
#semantic_results = validator.get_semantic_similarity()
cola_results = validator.get_cola_score()

Calculating COLA scores:   0%|          | 0/2 [00:00<?, ?it/s]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Calculating COLA scores: 100%|██████████| 2/2 [00:01<00:00,  1.58it/s]

In [6]:
#semantic_results

In [7]:
cola_results

                    cola_score
SOCManageability25    0.963508
SOCMeaningfulness8    0.960390

In [8]:
results = validator.run_validation()

======================================================================
Running Complete Validation for soc Questionnaire
======================================================================

Running model evaluation with 16 question variants...

Evaluating models:   0%|          | 0/20 [00:00<?, ?it/s]The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.

Evaluating model: typeform/distilbert-base-uncased-mnli

The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:15<00:00,  1.03it/s]
Evaluating models:   5%|▌         | 1/20 [00:15<05:02, 15.90s/it]

Evaluating model: typeform/mobilebert-uncased-mnli

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  6.95it/s]
Evaluating models:  10%|█         | 2/20 [00:19<02:31,  8.41s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: MoritzLaurer/DeBERTa-v3-large-mnli-fever-anli-ling-wanli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  6.15it/s]
Evaluating models:  15%|█▌        | 3/20 [00:22<01:46,  6.25s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: cross-encoder/nli-deberta-base

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  7.10it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  20%|██        | 4/20 [00:25<01:19,  4.98s/it]

Evaluating model: MoritzLaurer/mDeBERTa-v3-base-mnli-xnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  7.24it/s]
Evaluating models:  25%|██▌       | 5/20 [00:28<01:03,  4.24s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: cross-encoder/nli-MiniLM2-L6-H768

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  7.59it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  30%|███       | 6/20 [00:31<00:52,  3.78s/it]

Evaluating model: navteca/bart-large-mnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  7.28it/s]
Evaluating models:  35%|███▌      | 7/20 [00:35<00:47,  3.69s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: digitalepidemiologylab/covid-twitter-bert-v2-mnli

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  6.82it/s]
Evaluating models:  40%|████      | 8/20 [00:38<00:43,  3.62s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: joeddav/bart-large-mnli-yahoo-answers

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  6.96it/s]
Evaluating models:  45%|████▌     | 9/20 [00:42<00:39,  3.56s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: Narsil/deberta-large-mnli-zero-cls

Some weights of the model checkpoint at Narsil/deberta-large-mnli-zero-cls were not used when initializing DebertaForSequenceClassification: ['config']
- This IS expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  6.65it/s]
Evaluating models:  50%|█████     | 10/20 [00:45<00:35,  3.54s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: joeddav/xlm-roberta-large-xnli

Some weights of the model checkpoint at joeddav/xlm-roberta-large-xnli were not used when initializing XLMRobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  6.93it/s]
Evaluating models:  55%|█████▌    | 11/20 [00:49<00:34,  3.80s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: katanemo/bart-large-mnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  6.65it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  60%|██████    | 12/20 [00:53<00:29,  3.72s/it]

Evaluating model: mjwong/e5-large-mnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  7.17it/s]
Evaluating models:  65%|██████▌   | 13/20 [00:56<00:24,  3.46s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: mjwong/multilingual-e5-large-xnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  7.05it/s]
Evaluating models:  70%|███████   | 14/20 [00:59<00:21,  3.51s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: navteca/nli-deberta-v3-large

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  6.09it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  75%|███████▌  | 15/20 [01:03<00:18,  3.64s/it]

Evaluating model: symanto/mpnet-base-snli-mnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  7.44it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models:  80%|████████  | 16/20 [01:06<00:13,  3.32s/it]

Evaluating model: valhalla/distilbart-mnli-12-6

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  7.39it/s]
Evaluating models:  85%|████████▌ | 17/20 [01:09<00:09,  3.25s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: facebook/bart-large-mnli

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  7.23it/s]
Evaluating models:  90%|█████████ | 18/20 [01:12<00:06,  3.27s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: utahnlp/mnli_microsoft_deberta-v3-large_seed-3

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  6.31it/s]
Evaluating models:  95%|█████████▌| 19/20 [01:16<00:03,  3.28s/it]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: FacebookAI/roberta-large-mnli

Some weights of the model checkpoint at FacebookAI/roberta-large-mnli were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions: 100%|██████████| 16/16 [00:02<00:00,  7.02it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating models: 100%|██████████| 20/20 [01:19<00:00,  3.96s/it]

✓ Model evaluation complete. Results saved to: results/soc_mnli_results.csv

======================================================================
Calculating Content Validity Metrics
======================================================================

✓ Content validity metrics saved to: results/linguistic_acceptability.csv

Content Validity Results:
                        semantic_similarity  cola_score  silhouette_score
Q
SOCComprehensibility5              0.710211    0.959107          0.354676
SOCComprehensibility21             0.723456    0.979871          0.505377
SOCMeaningfulness4                 0.471769    0.976486          0.542615
SOCMeaningfulness16                0.797439    0.949567          0.600885
SOCManageability6                  0.668519    0.929842          0.646270
SOCMeaningfulness8                 0.342296    0.960390          0.701044
SOCComprehensibility19             0.660340    0.938545          0.724342
SOCManageability25                 0.467416    0.963508          0.740193
SOCManageability9                  0.766033    0.979992          0.747884
SOCComprehensibility12             0.671046    0.967319          0.756413
SOCComprehensibility26             0.680042    0.969996          0.770651
SOCManageability29                 0.701203    0.977136          0.797551
SOCMeaningfulness28                0.688243    0.976539          0.839738

======================================================================
Calculating Internal Consistency (Cronbach's Alpha)
======================================================================

Cronbach Alpha:
Comprehensibility: (0.594590714846366, array([0.224, 0.819]))
Manageability: (0.8335908891339947, array([0.671, 0.927]))
Meaningfulness: (0.8709068291958897, array([0.745, 0.943]))

soc Overall: (0.9024630776068231, array([0.825, 0.955]))

======================================================================
Calculating Factor Correlations
======================================================================

✓ Factor correlations (spearman):
                  Comprehensibility Manageability Meaningfulness  soc
Comprehensibility                 -           ***            ***  ***
Manageability                 0.922             -            ***  ***
Meaningfulness                0.735         0.857              -  ***
soc                           0.928         0.977          0.917    -

======================================================================
Validation Complete!
======================================================================
Results saved in: results

In [9]:
results.keys()

dict_keys(['results_csv', 'content_validity', 'cronbach_alpha', 'correlations'])

In [10]:
results['results_csv']

PosixPath('results/soc_mnli_results.csv')

In [11]:
results['content_validity']

                        semantic_similarity  cola_score  silhouette_score
Q
SOCComprehensibility5              0.710211    0.959107          0.354676
SOCComprehensibility21             0.723456    0.979871          0.505377
SOCMeaningfulness4                 0.471769    0.976486          0.542615
SOCMeaningfulness16                0.797439    0.949567          0.600885
SOCManageability6                  0.668519    0.929842          0.646270
SOCMeaningfulness8                 0.342296    0.960390          0.701044
SOCComprehensibility19             0.660340    0.938545          0.724342
SOCManageability25                 0.467416    0.963508          0.740193
SOCManageability9                  0.766033    0.979992          0.747884
SOCComprehensibility12             0.671046    0.967319          0.756413
SOCComprehensibility26             0.680042    0.969996          0.770651
SOCManageability29                 0.701203    0.977136          0.797551
SOCMeaningfulness28                0.688243    0.976539          0.839738

In [12]:
semantic_results = validator.get_semantic_similarity()
cola_results = validator.get_cola_score()

Calculating semantic similarity: 100%|██████████| 2/2 [00:00<00:00,  2.16it/s]
Calculating COLA scores: 100%|██████████| 2/2 [00:00<00:00,  2.75it/s]

In [13]:
cola_results

                    cola_score
SOCManageability25    0.963508
SOCMeaningfulness8    0.960390

In [14]:
results['cronbach_alpha']["overall"] # 0.9012972835805702

(0.9024630776068231, array([0.825, 0.955]))

In [15]:
# results['cronbach_alpha']["factors"]

In [16]:
data_df = results['cronbach_alpha']['data_df']
validator.test_question_affect_on_cronbach_alpha(data_df)

All Questions Alpha: (0.9024630776068231, array([0.825, 0.955]))
without: SOCComprehensibility12 Alpha: (0.8931712934487543, array([0.808, 0.951]))
without: SOCComprehensibility19 Alpha: (0.8929022209391851, array([0.808, 0.951]))
without: SOCComprehensibility21 Alpha: (0.891214789751294, array([0.805, 0.95 ]))
without: SOCComprehensibility26 Alpha: (0.8919200547523988, array([0.806, 0.95 ]))
without: SOCComprehensibility5 Alpha: (0.9421163645136853, array([0.896, 0.973]))
without: SOCManageability25 Alpha: (0.8840637156418081, array([0.792, 0.947]))
without: SOCManageability29 Alpha: (0.889844527553969, array([0.802, 0.949]))
without: SOCManageability6 Alpha: (0.8983813342049685, array([0.818, 0.953]))
without: SOCManageability9 Alpha: (0.8856013994553197, array([0.795, 0.947]))
without: SOCMeaningfulness16 Alpha: (0.8981003848781197, array([0.817, 0.953]))
without: SOCMeaningfulness28 Alpha: (0.8944033102641682, array([0.81 , 0.951]))
without: SOCMeaningfulness4 Alpha: (0.8880242319387529, array([0.799, 0.948]))
without: SOCMeaningfulness8 Alpha: (0.8852607212240045, array([0.794, 0.947]))

In [17]:
data_df

Q,SOCComprehensibility12,SOCComprehensibility19,SOCComprehensibility21,SOCComprehensibility26,SOCComprehensibility5,SOCManageability25,SOCManageability29,SOCManageability6,SOCManageability9,SOCMeaningfulness16,SOCMeaningfulness28,SOCMeaningfulness4,SOCMeaningfulness8
model,,,,,,,,,,,,,
FacebookAI/roberta-large-mnli,0.057393,0.102394,0.043261,0.160075,0.014639,0.054078,0.055597,0.023585,0.077700,0.081886,0.097010,0.045828,0.064218
MoritzLaurer/DeBERTa-v3-large-mnli-fever-anli-ling-wanli,0.034633,0.069080,0.017287,0.108313,-0.071734,0.025528,0.027166,-0.000109,0.014495,0.037742,0.052886,0.022864,0.053846
MoritzLaurer/mDeBERTa-v3-base-mnli-xnli,0.075739,0.080192,0.039093,0.143863,0.035201,0.057443,0.069968,0.049213,0.078347,0.084370,0.110719,0.051617,0.079323
Narsil/deberta-large-mnli-zero-cls,0.054664,0.089995,0.043513,0.169822,0.002746,0.049654,0.037275,0.004131,0.065705,0.058437,0.100260,0.059789,0.065346
cross-encoder/nli-MiniLM2-L6-H768,0.059665,0.077176,0.017215,0.150220,0.090654,0.066324,0.050260,0.026650,0.070501,0.050655,0.076322,0.037120,0.060793
cross-encoder/nli-deberta-base,0.058735,0.087624,0.048572,0.152860,0.070071,0.060839,0.067892,0.063289,0.085870,0.080200,0.102906,0.053495,0.076831
digitalepidemiologylab/covid-twitter-bert-v2-mnli,0.048190,0.045942,0.036595,0.143584,-0.009779,0.062420,0.059141,-0.031420,0.078470,0.070480,0.102390,0.059826,0.063113
facebook/bart-large-mnli,0.101533,0.109372,0.071460,0.161827,-0.033665,0.093704,0.079556,0.071757,0.096856,0.071271,0.113891,0.075710,0.109155
joeddav/bart-large-mnli-yahoo-answers,0.026124,0.041411,0.014840,0.070200,-0.002965,0.013037,0.018943,0.007542,0.029961,0.021856,0.042503,0.023514,0.039021
joeddav/xlm-roberta-large-xnli,0.055459,0.100943,0.021074,0.167333,0.040916,0.081216,0.042915,0.001862,0.086149,0.083594,0.112849,0.051873,0.069787
katanemo/bart-large-mnli,0.101533,0.109372,0.071460,0.161827,-0.033665,0.093704,0.079556,0.071757,0.096856,0.071271,0.113891,0.075710,0.109155
mjwong/e5-large-mnli,0.051029,0.071361,0.032630,0.133354,0.064346,0.047713,0.037160,0.025087,0.064061,0.044441,0.062067,0.044600,0.047163
mjwong/multilingual-e5-large-xnli,0.045119,0.056781,0.010249,0.077909,0.003482,0.025162,0.023823,0.036433,0.052062,0.053901,0.093752,0.003630,0.035709
navteca/bart-large-mnli,0.101533,0.109372,0.071460,0.161827,-0.033665,0.093704,0.079556,0.071757,0.096856,0.071271,0.113891,0.075710,0.109155
navteca/nli-deberta-v3-large,0.063820,0.020958,0.010492,0.047892,-0.005853,0.053984,0.038309,0.008828,0.040541,0.083023,0.119059,0.037603,0.030939
symanto/mpnet-base-snli-mnli,0.082585,0.085869,0.040565,0.149433,0.065026,0.065515,0.044826,0.113303,0.068540,0.061291,0.091575,0.056683,0.071642
typeform/distilbert-base-uncased-mnli,0.065265,0.091390,0.046080,0.124956,0.126867,0.100767,0.083627,0.081896,0.077771,0.085396,0.114775,0.077104,0.103326
typeform/mobilebert-uncased-mnli,0.039624,0.067371,0.043372,0.154198,0.119014,0.083529,0.045744,0.068148,0.080686,0.078632,0.097792,0.071095,0.082238
utahnlp/mnli_microsoft_deberta-v3-large_seed-3,0.046909,0.092226,0.024174,0.093674,-0.005708,0.053373,0.053197,0.003376,0.054732,0.082362,0.081187,0.019448,0.056244
valhalla/distilbart-mnli-12-6,0.102149,0.096033,0.040317,0.152808,-0.001536,0.080973,0.060467,0.007920,0.096785,0.070284,0.110654,0.062704,0.103038

In [18]:
results['correlations']

                  Comprehensibility Manageability Meaningfulness  soc
Comprehensibility                 -           ***            ***  ***
Manageability                 0.922             -            ***  ***
Meaningfulness                0.735         0.857              -  ***
soc                           0.928         0.977          0.917    -