In [23]:
import os
os.chdir('/home/shistikk/qpsychometric')
print(os.getcwd())

/home/shistikk/qpsychometric

In [2]:
from qpsychometric.questionnaire_clm_validator import QuestionnaireCLMValidator
from qpsychometric.mental_health.sense_of_coherence import soc_questionnaire

/home/shistikk/.conda/envs/astrin/lib/python3.12/site-packages/torch/utils/_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(
2026-07-12 13:54:55.376511: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-07-12 13:54:55.397773: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-07-12 13:54:55.404375: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-07-12 13:54:55.420513: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-07-12 13:54:57.110138: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [3]:
# Import soc questions
soc_qmnli_df = soc_questionnaire['QCLM']
soc_questions = soc_qmnli_df.get_questions()

soc_factors = list(set([q()._descriptor['Factor'] for q in soc_questions]))

In [4]:
soc_questions

[qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ4,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ5,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ6,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ8,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ9,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ12,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ16,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ19,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ21,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ25,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ26,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ28,
 qpsychometric.mental_health.sense_of_coherence.soc_qclm.SOCQ29]

In [5]:
# Create validator instance
validator = QuestionnaireCLMValidator(
    questionnaire_name="soc",
    questions=soc_questions,
    factors=soc_factors,
    result_path="results/",
    update=True
)

Loading validation models...

/home/shistikk/.conda/envs/astrin/lib/python3.12/site-packages/transformers/convert_slow_tokenizer.py:559: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Device set to use cuda:0

Models loaded successfully.
Splitting 13 questions...
Generated 104 question variants.
Initialized soc CLM Validator:
  - Questions: 13
  - Factors: ['Meaningfulness', 'Manageability', 'Comprehensibility']
  - Scales: ['answer']
  - Index: ['question']
  - Device: 0
  - Instruct (chat) models: 10
  - Result path: results

In [6]:
results = validator.run_validation()

======================================================================
Running Complete CLM Validation for soc Questionnaire
======================================================================

Running model evaluation with 104 question variants...

Evaluating models:   0%|          | 0/16 [00:00<?, ?it/s]

Evaluating model: google/gemma-2-2b  (mode=raw, type=base)

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: google/gemma-2-9b  (mode=raw, type=base)

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]

Device set to use cuda:0

Error evaluating google/gemma-2-9b: CUDA out of memory. Tried to allocate 196.00 MiB. GPU 0 has a total capacity of 23.52 GiB of which 189.75 MiB is free. Including non-PyTorch memory, this process has 23.32 GiB memory in use. Of the allocated memory 22.85 GiB is allocated by PyTorch, and 20.68 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Evaluating model: google/gemma-3-270m  (mode=raw, type=base)

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: meta-llama/Llama-3.2-1B  (mode=raw, type=base)

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: meta-llama/Llama-3.2-3B  (mode=raw, type=base)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: microsoft/MediPhi  (mode=raw, type=base)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: microsoft/MediPhi-PubMed  (mode=raw, type=base)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.

Evaluating model: Qwen/Qwen2.5-3B  (mode=raw, type=base)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: google/gemma-3-1b-it  (mode=chat, type=chat)

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: google/gemma-3-270m-it  (mode=chat, type=chat)

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: meta-llama/Llama-3.2-1B-Instruct  (mode=chat, type=chat)

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: meta-llama/Llama-3.2-3B-Instruct  (mode=chat, type=chat)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: microsoft/MediPhi-Instruct  (mode=chat, type=chat)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: microsoft/Phi-4-mini-instruct  (mode=chat, type=chat)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: Qwen/Qwen3-1.7B  (mode=chat, type=chat)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: Qwen/Qwen3-4B  (mode=chat, type=chat)

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/104 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

✓ Model evaluation complete. Results saved to: results/soc_clm_results.csv

======================================================================
Calculating Content Validity Metrics (all models)
======================================================================

✓ Content validity metrics saved to: results/linguistic_acceptability.csv

Content Validity Results:
                        semantic_similarity  cola_score  silhouette_score
Q
SOCComprehensibility19             0.568049    0.922385          0.262792
SOCComprehensibility5              0.544072    0.889751          0.264297
SOCManageability29                 0.823751    0.837241          0.280270
SOCComprehensibility21             0.652107    0.943529          0.289605
SOCManageability25                 0.561659    0.914644          0.298846
SOCComprehensibility26             0.632430    0.917530          0.303265
SOCManageability9                  0.652218    0.925827          0.324635
SOCMeaningfulness4                 0.659520    0.861447          0.340733
SOCMeaningfulness16                0.575587    0.946663          0.354521
SOCComprehensibility12             0.657011    0.949665          0.366425
SOCManageability6                  0.606516    0.957582          0.383684
SOCMeaningfulness28                0.770533    0.948243          0.393463
SOCMeaningfulness8                 0.341661    0.920722          0.431906

======================================================================
Calculating Internal Consistency (Cronbach's Alpha, all models)
======================================================================

Cronbach Alpha:
Meaningfulness: (0.7852780283545375, array([0.529, 0.919]))
Manageability: (0.7242349116444766, array([0.395, 0.897]))
Comprehensibility: (0.9042687282494413, array([0.798, 0.964]))

soc Overall: (0.9293826883135408, array([0.863, 0.972]))

======================================================================
Calculating Factor Correlations (all models)
======================================================================

✓ Factor correlations (spearman):
                  Meaningfulness Manageability Comprehensibility  soc
Meaningfulness                 -           ***                **  ***
Manageability              0.861             -                 *  ***
Comprehensibility          0.725         0.629                 -  ***
soc                        0.904         0.843             0.896    -

======================================================================
Validation Complete!
======================================================================
Results saved in: results

In [7]:
results.keys()

dict_keys(['results_csv', 'content_validity', 'cronbach_alpha', 'correlations'])

In [8]:
results_csv = results['results_csv']

In [9]:
from pathlib import Path

p = Path('results/soc_clm_results.csv')

In [10]:
import pandas as pd
df = pd.read_csv(p)
len(set(df["model"]))

15

In [11]:
set(df["model"])

{'Qwen/Qwen2.5-3B',
 'Qwen/Qwen3-1.7B',
 'Qwen/Qwen3-4B',
 'google/gemma-2-2b',
 'google/gemma-3-1b-it',
 'google/gemma-3-270m',
 'google/gemma-3-270m-it',
 'meta-llama/Llama-3.2-1B',
 'meta-llama/Llama-3.2-1B-Instruct',
 'meta-llama/Llama-3.2-3B',
 'meta-llama/Llama-3.2-3B-Instruct',
 'microsoft/MediPhi',
 'microsoft/MediPhi-Instruct',
 'microsoft/MediPhi-PubMed',
 'microsoft/Phi-4-mini-instruct'}

## Analysis - base models

In [12]:
content_validity_base = validator.calc_content_validity(results_csv, model_type='base')
content_validity_base

✓ Content validity metrics (base) saved to: results/linguistic_acceptability_base.csv

                        semantic_similarity  cola_score  silhouette_score
Q
SOCManageability25                 0.561659    0.914644          0.264864
SOCMeaningfulness4                 0.659520    0.861447          0.275726
SOCMeaningfulness16                0.575587    0.946663          0.277245
SOCComprehensibility5              0.544072    0.889751          0.279887
SOCManageability9                  0.652218    0.925827          0.284247
SOCMeaningfulness28                0.770533    0.948243          0.314045
SOCComprehensibility19             0.568049    0.922385          0.339580
SOCManageability29                 0.823751    0.837241          0.342073
SOCComprehensibility26             0.632430    0.917530          0.398804
SOCComprehensibility12             0.657011    0.949665          0.413177
SOCMeaningfulness8                 0.341661    0.920722          0.430658
SOCComprehensibility21             0.652107    0.943529          0.445706
SOCManageability6                  0.606516    0.957582          0.537314

In [13]:
alpha_base = validator.calc_cronbach_alpha(results_csv, model_type='base')
print('overall:', alpha_base['overall'])
print('factors:', alpha_base['factors'])

Cronbach Alpha (base):
Meaningfulness: (0.7297899937085761, array([0.13 , 0.948]))
Manageability: (0.5572096453811912, array([-0.426,  0.915]))
Comprehensibility: (0.8989127595581087, array([0.697, 0.98 ]))

soc Overall (base): (0.915093320118266, array([0.78 , 0.983]))
overall: (0.915093320118266, array([0.78 , 0.983]))
factors: {'Meaningfulness': (0.7297899937085761, array([0.13 , 0.948])), 'Manageability': (0.5572096453811912, array([-0.426,  0.915])), 'Comprehensibility': (0.8989127595581087, array([0.697, 0.98 ]))}

In [14]:
validator.test_question_affect_on_cronbach_alpha(alpha_base['data_df'])

All Questions Alpha: (0.915093320118266, array([0.78 , 0.983]))
without: SOCComprehensibility12 Alpha: (0.8939488449564198, array([0.724, 0.979]))
without: SOCComprehensibility19 Alpha: (0.8985603750787466, array([0.736, 0.98 ]))
without: SOCComprehensibility21 Alpha: (0.913555917198152, array([0.775, 0.983]))
without: SOCComprehensibility26 Alpha: (0.9053520855248244, array([0.753, 0.981]))
without: SOCComprehensibility5 Alpha: (0.9087690762206946, array([0.762, 0.982]))
without: SOCManageability25 Alpha: (0.910133320561723, array([0.766, 0.982]))
without: SOCManageability29 Alpha: (0.9172838640883003, array([0.784, 0.983]))
without: SOCManageability6 Alpha: (0.9136274884006834, array([0.775, 0.983]))
without: SOCManageability9 Alpha: (0.9133876949013862, array([0.774, 0.982]))
without: SOCMeaningfulness16 Alpha: (0.9062483169811795, array([0.756, 0.981]))
without: SOCMeaningfulness28 Alpha: (0.8941417752875715, array([0.724, 0.979]))
without: SOCMeaningfulness4 Alpha: (0.9284707669857396, array([0.814, 0.986]))
without: SOCMeaningfulness8 Alpha: (0.8977528638984317, array([0.733, 0.979]))

In [15]:
correlations_base = validator.calc_correlations(results_csv, model_type='base')
correlations_base

✓ Factor correlations (base) (spearman):
                  Meaningfulness Manageability Comprehensibility  soc
Meaningfulness                 -             *                 *    *
Manageability              0.857             -                 *    *
Comprehensibility          0.786         0.786                 -  ***
soc                        0.821         0.857             0.964    -

                  Meaningfulness Manageability Comprehensibility  soc
Meaningfulness                 -             *                 *    *
Manageability              0.857             -                 *    *
Comprehensibility          0.786         0.786                 -  ***
soc                        0.821         0.857             0.964    -

## Analysis - instruct models

In [16]:
content_validity_chat = validator.calc_content_validity(results_csv, model_type='chat')
content_validity_chat

✓ Content validity metrics (chat) saved to: results/linguistic_acceptability_chat.csv

                        semantic_similarity  cola_score  silhouette_score
Q
SOCComprehensibility21             0.652107    0.943529          0.153016
SOCComprehensibility19             0.568049    0.922385          0.195602
SOCComprehensibility26             0.632430    0.917530          0.219669
SOCManageability29                 0.823751    0.837241          0.226193
SOCManageability6                  0.606516    0.957582          0.249258
SOCComprehensibility5              0.544072    0.889751          0.250655
SOCComprehensibility12             0.657011    0.949665          0.325516
SOCManageability25                 0.561659    0.914644          0.328580
SOCManageability9                  0.652218    0.925827          0.359974
SOCMeaningfulness4                 0.659520    0.861447          0.397615
SOCMeaningfulness16                0.575587    0.946663          0.422137
SOCMeaningfulness8                 0.341661    0.920722          0.432999
SOCMeaningfulness28                0.770533    0.948243          0.462953

In [17]:
alpha_chat = validator.calc_cronbach_alpha(results_csv, model_type='chat')
print('overall:', alpha_chat['overall'])
print('factors:', alpha_chat['factors'])

Cronbach Alpha (chat):
Meaningfulness: (0.8641771015756944, array([0.597, 0.969]))
Manageability: (0.8340518105696538, array([0.507, 0.963]))
Comprehensibility: (0.8719319033708262, array([0.644, 0.971]))

soc Overall (chat): (0.9170853609774383, array([0.798, 0.98 ]))
overall: (0.9170853609774383, array([0.798, 0.98 ]))
factors: {'Meaningfulness': (0.8641771015756944, array([0.597, 0.969])), 'Manageability': (0.8340518105696538, array([0.507, 0.963])), 'Comprehensibility': (0.8719319033708262, array([0.644, 0.971]))}

In [18]:
validator.test_question_affect_on_cronbach_alpha(alpha_chat['data_df'])

All Questions Alpha: (0.9170853609774383, array([0.798, 0.98 ]))
without: SOCComprehensibility12 Alpha: (0.9171579140056058, array([0.796, 0.98 ]))
without: SOCComprehensibility19 Alpha: (0.9145070420062346, array([0.79, 0.98]))
without: SOCComprehensibility21 Alpha: (0.9108450096284703, array([0.781, 0.979]))
without: SOCComprehensibility26 Alpha: (0.9142848905382447, array([0.789, 0.98 ]))
without: SOCComprehensibility5 Alpha: (0.9126204008273822, array([0.785, 0.979]))
without: SOCManageability25 Alpha: (0.9031068372209085, array([0.762, 0.977]))
without: SOCManageability29 Alpha: (0.9124519648770533, array([0.785, 0.979]))
without: SOCManageability6 Alpha: (0.9137556356940475, array([0.788, 0.98 ]))
without: SOCManageability9 Alpha: (0.9076421019552599, array([0.773, 0.978]))
without: SOCMeaningfulness16 Alpha: (0.9132724207883645, array([0.787, 0.979]))
without: SOCMeaningfulness28 Alpha: (0.8996043107733732, array([0.753, 0.976]))
without: SOCMeaningfulness4 Alpha: (0.9011013007442745, array([0.757, 0.977]))
without: SOCMeaningfulness8 Alpha: (0.9153255073951035, array([0.792, 0.98 ]))

In [19]:
correlations_chat = validator.calc_correlations(results_csv, model_type='chat')
correlations_chat

✓ Factor correlations (chat) (spearman):
                  Meaningfulness Manageability Comprehensibility soc
Meaningfulness                 -            **                     *
Manageability              0.881             -                     *
Comprehensibility          0.333         0.381                 -   *
soc                        0.762         0.833             0.738   -

                  Meaningfulness Manageability Comprehensibility soc
Meaningfulness                 -            **                     *
Manageability              0.881             -                     *
Comprehensibility          0.333         0.381                 -   *
soc                        0.762         0.833             0.738   -

## Item-level linguistic metrics (model-independent)

In [20]:
semantic_results = validator.get_semantic_similarity()
cola_results = validator.get_cola_score()

Calculating semantic similarity:   0%|          | 0/13 [00:00<?, ?it/s]

Calculating COLA scores:   0%|          | 0/13 [00:00<?, ?it/s]

In [21]:
cola_results

                        cola_score
SOCMeaningfulness4        0.861447
SOCComprehensibility5     0.889751
SOCManageability6         0.957582
SOCMeaningfulness8        0.920722
SOCManageability9         0.925827
SOCComprehensibility12    0.949665
SOCMeaningfulness16       0.946663
SOCComprehensibility19    0.922385
SOCComprehensibility21    0.943529
SOCManageability25        0.914644
SOCComprehensibility26    0.917530
SOCMeaningfulness28       0.948243
SOCManageability29        0.837241

In [22]:
semantic_results

                        semantic_similarity
SOCMeaningfulness4                 0.659520
SOCComprehensibility5              0.544072
SOCManageability6                  0.606516
SOCMeaningfulness8                 0.341661
SOCManageability9                  0.652218
SOCComprehensibility12             0.657011
SOCMeaningfulness16                0.575587
SOCComprehensibility19             0.568049
SOCComprehensibility21             0.652107
SOCManageability25                 0.561659
SOCComprehensibility26             0.632430
SOCMeaningfulness28                0.770533
SOCManageability29                 0.823751