In [4]:
from qpsychometric.questionnaire_validator import QuestionnaireValidator
from qpsychometric.mental_health.patient_health_questionnaire import phq_questionnaire

In [5]:
# Import phq questions
phq_qmnli_df = phq_questionnaire['QMNLI']
phq_questions = phq_qmnli_df.get_questions()

phq_factors = list(set([q()._descriptor['Factor'] for q in phq_questions]))

In [6]:
# Create validator instance
validator = QuestionnaireValidator(
    questionnaire_name="phq",
    questions=phq_questions,
    factors=phq_factors,
    result_path="results/",
)

results = validator.run_validation()

Loading validation models...

/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py:560: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Models loaded successfully.
Splitting 9 questions...
Generated 72 question variants.
Initialized phq Validator:
  - Questions: 9
  - Factors: ['PHQ9']
  - Scales: ['frequency']
  - Index: ['index']
  - Device: 0
  - Result path: results

======================================================================
Running Complete Validation for phq Questionnaire
======================================================================

Running model evaluation with 72 question variants...

Evaluating models:   0%|          | 0/19 [00:00<?, ?it/s]The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.

Evaluating model: typeform/distilbert-base-uncased-mnli

The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Processing questions:  44%|████▍     | 32/72 [00:34<00:42,  1.06s/it]
Evaluating models:   0%|          | 0/19 [00:34<?, ?it/s]

KeyboardInterrupt:

In [ ]:
results.keys()

dict_keys(['results_csv', 'content_validity', 'cronbach_alpha', 'correlations'])

In [ ]:
results['results_csv']

PosixPath('results/phq_mnli_results.csv')

In [ ]:
import pandas as pd
df = pd.read_csv("results/phq_mnli_results.csv")
len(set(df["model"]))

13

In [ ]:
results['content_validity']

           semantic_similarity  cola_score  silhouette_score
Q
PHQ9PHQ99             0.492422    0.776981          0.382876
PHQ9PHQ98             0.690634    0.786128          0.506068
PHQ9PHQ95             0.694252    0.937892          0.551488
PHQ9PHQ92             0.580788    0.927962          0.621872
PHQ9PHQ94             0.639825    0.927437          0.665106
PHQ9PHQ96             0.529733    0.936219          0.690903
PHQ9PHQ93             0.631983    0.948883          0.699025
PHQ9PHQ91             0.614382    0.830769          0.724996
PHQ9PHQ97             0.638854    0.929435          0.783064

In [ ]:
results['cronbach_alpha']["overall"]

(0.873445496559791, array([0.736, 0.955]))

In [ ]:
results['cronbach_alpha']["factors"]

{'PHQ9': (0.873445496559791, array([0.736, 0.955]))}

In [ ]:
results['correlations']

     PHQ9  phq
PHQ9    -  ***
phq   1.0    -