In [1]:
import os
os.chdir('/home/shistikk/qpsychometric')
print(os.getcwd())

/home/shistikk/qpsychometric

In [2]:
# pip show qlatent

In [3]:
from qpsychometric.questionnaire_clm_validator import QuestionnaireCLMValidator
from qpsychometric.mental_health.patient_health_questionnaire import phq_questionnaire

/home/shistikk/.conda/envs/astrin/lib/python3.12/site-packages/torch/utils/_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(
2026-07-12 13:30:09.090658: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-07-12 13:30:09.355708: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-07-12 13:30:09.432262: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-07-12 13:30:09.951012: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-07-12 13:30:12.331881: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [4]:
# Import phq questions
phq_qclm_df = phq_questionnaire['QCLM']
phq_questions = phq_qclm_df.get_questions()

phq_factors = list(set([q()._descriptor['Factor'] for q in phq_questions]))

In [5]:
phq_questions[2]()._dimensions

{'answer': {'never': -4,
  'very rarely': -3,
  'seldom': -2,
  'rarely': -2,
  'frequently': 2,
  'often': 2,
  'very frequently': 3,
  'always': 4},
 'question': {'trouble falling asleep': 0.5,
  'trouble staying asleep': 0.5,
  'been resting well': -0.5,
  'been sleeping well': -0.5}}

In [6]:
vars(phq_questions[2]())

{'_dimensions': {'answer': {'never': -4,
   'very rarely': -3,
   'seldom': -2,
   'rarely': -2,
   'frequently': 2,
   'often': 2,
   'very frequently': 3,
   'always': 4},
  'question': {'trouble falling asleep': 0.5,
   'trouble staying asleep': 0.5,
   'been resting well': -0.5,
   'been sleeping well': -0.5}},
 '_field_names': ['answer', 'question'],
 '_scale': 'answer',
 '_index': ['question'],
 '_descriptor': {'Questionnair': 'PHQ9',
  'Factor': 'Q',
  'Ordinal': 3,
  'Original': 'Over the last 2 weeks, how often have you been bothered by the following problems? Trouble falling asleep, staying asleep, or sleeping too much',
  'scale': 'answer',
  'index': "['question']",
  'query': 'Question: Over the last 2 weeks, how often you had {question}? Answer: {answer}'},
 '_keywords': {'answer': ['never',
   'very rarely',
   'seldom',
   'rarely',
   'frequently',
   'often',
   'very frequently',
   'always'],
  'question': ['trouble falling asleep',
   'trouble staying asleep',
   'been resting well',
   'been sleeping well']},
 '_keywords_indices': {'answer': {'never': 0,
   'very rarely': 1,
   'seldom': 2,
   'rarely': 3,
   'frequently': 4,
   'often': 5,
   'very frequently': 6,
   'always': 7},
  'question': {'trouble falling asleep': 0,
   'trouble staying asleep': 1,
   'been resting well': 2,
   'been sleeping well': 3}},
 '_dimshape': (8, 4),
 '_keywords_grid': [('never', 'trouble falling asleep'),
  ('never', 'trouble staying asleep'),
  ('never', 'been resting well'),
  ('never', 'been sleeping well'),
  ('very rarely', 'trouble falling asleep'),
  ('very rarely', 'trouble staying asleep'),
  ('very rarely', 'been resting well'),
  ('very rarely', 'been sleeping well'),
  ('seldom', 'trouble falling asleep'),
  ('seldom', 'trouble staying asleep'),
  ('seldom', 'been resting well'),
  ('seldom', 'been sleeping well'),
  ('rarely', 'trouble falling asleep'),
  ('rarely', 'trouble staying asleep'),
  ('rarely', 'been resting well'),
  ('rarely', 'been sleeping well'),
  ('frequently', 'trouble falling asleep'),
  ('frequently', 'trouble staying asleep'),
  ('frequently', 'been resting well'),
  ('frequently', 'been sleeping well'),
  ('often', 'trouble falling asleep'),
  ('often', 'trouble staying asleep'),
  ('often', 'been resting well'),
  ('often', 'been sleeping well'),
  ('very frequently', 'trouble falling asleep'),
  ('very frequently', 'trouble staying asleep'),
  ('very frequently', 'been resting well'),
  ('very frequently', 'been sleeping well'),
  ('always', 'trouble falling asleep'),
  ('always', 'trouble staying asleep'),
  ('always', 'been resting well'),
  ('always', 'been sleeping well')],
 '_keywords_map': [{'answer': 'never', 'question': 'trouble falling asleep'},
  {'answer': 'never', 'question': 'trouble staying asleep'},
  {'answer': 'never', 'question': 'been resting well'},
  {'answer': 'never', 'question': 'been sleeping well'},
  {'answer': 'very rarely', 'question': 'trouble falling asleep'},
  {'answer': 'very rarely', 'question': 'trouble staying asleep'},
  {'answer': 'very rarely', 'question': 'been resting well'},
  {'answer': 'very rarely', 'question': 'been sleeping well'},
  {'answer': 'seldom', 'question': 'trouble falling asleep'},
  {'answer': 'seldom', 'question': 'trouble staying asleep'},
  {'answer': 'seldom', 'question': 'been resting well'},
  {'answer': 'seldom', 'question': 'been sleeping well'},
  {'answer': 'rarely', 'question': 'trouble falling asleep'},
  {'answer': 'rarely', 'question': 'trouble staying asleep'},
  {'answer': 'rarely', 'question': 'been resting well'},
  {'answer': 'rarely', 'question': 'been sleeping well'},
  {'answer': 'frequently', 'question': 'trouble falling asleep'},
  {'answer': 'frequently', 'question': 'trouble staying asleep'},
  {'answer': 'frequently', 'question': 'been resting well'},
  {'answer': 'frequently', 'question': 'been sleeping well'},
  {'answer': 'often', 'question': 'trouble falling asleep'},
  {'answer': 'often', 'question': 'trouble staying asleep'},
  {'answer': 'often', 'question': 'been resting well'},
  {'answer': 'often', 'question': 'been sleeping well'},
  {'answer': 'very frequently', 'question': 'trouble falling asleep'},
  {'answer': 'very frequently', 'question': 'trouble staying asleep'},
  {'answer': 'very frequently', 'question': 'been resting well'},
  {'answer': 'very frequently', 'question': 'been sleeping well'},
  {'answer': 'always', 'question': 'trouble falling asleep'},
  {'answer': 'always', 'question': 'trouble staying asleep'},
  {'answer': 'always', 'question': 'been resting well'},
  {'answer': 'always', 'question': 'been sleeping well'}],
 '_keywords_grid_idx': tensor([[0., 0.],
         [0., 1.],
         [0., 2.],
         [0., 3.],
         [1., 0.],
         [1., 1.],
         [1., 2.],
         [1., 3.],
         [2., 0.],
         [2., 1.],
         [2., 2.],
         [2., 3.],
         [3., 0.],
         [3., 1.],
         [3., 2.],
         [3., 3.],
         [4., 0.],
         [4., 1.],
         [4., 2.],
         [4., 3.],
         [5., 0.],
         [5., 1.],
         [5., 2.],
         [5., 3.],
         [6., 0.],
         [6., 1.],
         [6., 2.],
         [6., 3.],
         [7., 0.],
         [7., 1.],
         [7., 2.],
         [7., 3.]]),
 '_weights_grid':     answer  question
 0       -4       0.5
 1       -4       0.5
 2       -4      -0.5
 3       -4      -0.5
 4       -3       0.5
 5       -3       0.5
 6       -3      -0.5
 7       -3      -0.5
 8       -2       0.5
 9       -2       0.5
 10      -2      -0.5
 11      -2      -0.5
 12      -2       0.5
 13      -2       0.5
 14      -2      -0.5
 15      -2      -0.5
 16       2       0.5
 17       2       0.5
 18       2      -0.5
 19       2      -0.5
 20       2       0.5
 21       2       0.5
 22       2      -0.5
 23       2      -0.5
 24       3       0.5
 25       3       0.5
 26       3      -0.5
 27       3      -0.5
 28       4       0.5
 29       4       0.5
 30       4      -0.5
 31       4      -0.5,
 '_weights_flat': 0    -2.0
 1    -2.0
 2     2.0
 3     2.0
 4    -1.5
 5    -1.5
 6     1.5
 7     1.5
 8    -1.0
 9    -1.0
 10    1.0
 11    1.0
 12   -1.0
 13   -1.0
 14    1.0
 15    1.0
 16    1.0
 17    1.0
 18   -1.0
 19   -1.0
 20    1.0
 21    1.0
 22   -1.0
 23   -1.0
 24    1.5
 25    1.5
 26   -1.5
 27   -1.5
 28    2.0
 29    2.0
 30   -2.0
 31   -2.0
 dtype: float64,
 '_weights_dense': tensor([[-2.0000, -2.0000,  2.0000,  2.0000],
         [-1.5000, -1.5000,  1.5000,  1.5000],
         [-1.0000, -1.0000,  1.0000,  1.0000],
         [-1.0000, -1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000, -1.0000, -1.0000],
         [ 1.0000,  1.0000, -1.0000, -1.0000],
         [ 1.5000,  1.5000, -1.5000, -1.5000],
         [ 2.0000,  2.0000, -2.0000, -2.0000]], dtype=torch.float64),
 '_pdf':              answer                question  P    W
 0             never  trouble falling asleep  0 -2.0
 1             never  trouble staying asleep  0 -2.0
 2             never       been resting well  0  2.0
 3             never      been sleeping well  0  2.0
 4       very rarely  trouble falling asleep  0 -1.5
 5       very rarely  trouble staying asleep  0 -1.5
 6       very rarely       been resting well  0  1.5
 7       very rarely      been sleeping well  0  1.5
 8            seldom  trouble falling asleep  0 -1.0
 9            seldom  trouble staying asleep  0 -1.0
 10           seldom       been resting well  0  1.0
 11           seldom      been sleeping well  0  1.0
 12           rarely  trouble falling asleep  0 -1.0
 13           rarely  trouble staying asleep  0 -1.0
 14           rarely       been resting well  0  1.0
 15           rarely      been sleeping well  0  1.0
 16       frequently  trouble falling asleep  0  1.0
 17       frequently  trouble staying asleep  0  1.0
 18       frequently       been resting well  0 -1.0
 19       frequently      been sleeping well  0 -1.0
 20            often  trouble falling asleep  0  1.0
 21            often  trouble staying asleep  0  1.0
 22            often       been resting well  0 -1.0
 23            often      been sleeping well  0 -1.0
 24  very frequently  trouble falling asleep  0  1.5
 25  very frequently  trouble staying asleep  0  1.5
 26  very frequently       been resting well  0 -1.5
 27  very frequently      been sleeping well  0 -1.5
 28           always  trouble falling asleep  0  2.0
 29           always  trouble staying asleep  0  2.0
 30           always       been resting well  0 -2.0
 31           always      been sleeping well  0 -2.0,
 '_t': None,
 'model': None,
 '_template': 'Question: Over the last 2 weeks, how often you had {question}? Answer: {answer}'}

In [7]:
# Create validator instance
validator = QuestionnaireCLMValidator(
    questionnaire_name="phq",
    questions=phq_questions,
    factors=phq_factors,
    result_path="results/",
)

Loading validation models...

/home/shistikk/.conda/envs/astrin/lib/python3.12/site-packages/transformers/convert_slow_tokenizer.py:559: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Device set to use cuda:0

Models loaded successfully.
Splitting 9 questions...
Generated 72 question variants.
Initialized phq CLM Validator:
  - Questions: 9
  - Factors: ['Q']
  - Scales: ['answer']
  - Index: ['question']
  - Device: 0
  - Instruct (chat) models: 10
  - Result path: results

In [8]:
results = validator.run_validation()

======================================================================
Running Complete CLM Validation for phq Questionnaire
======================================================================

Running model evaluation with 72 question variants...

Evaluating models:   0%|          | 0/16 [00:00<?, ?it/s]

Evaluating model: google/gemma-2-2b  (mode=raw, type=base)

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: google/gemma-2-9b  (mode=raw, type=base)

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]

Device set to use cuda:0

Error evaluating google/gemma-2-9b: CUDA out of memory. Tried to allocate 196.00 MiB. GPU 0 has a total capacity of 23.52 GiB of which 189.75 MiB is free. Including non-PyTorch memory, this process has 23.32 GiB memory in use. Of the allocated memory 22.85 GiB is allocated by PyTorch, and 20.70 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Evaluating model: google/gemma-3-270m  (mode=raw, type=base)

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: meta-llama/Llama-3.2-1B  (mode=raw, type=base)

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: meta-llama/Llama-3.2-3B  (mode=raw, type=base)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: microsoft/MediPhi  (mode=raw, type=base)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: microsoft/MediPhi-PubMed  (mode=raw, type=base)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: Qwen/Qwen2.5-3B  (mode=raw, type=base)

Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: google/gemma-3-1b-it  (mode=chat, type=chat)

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: google/gemma-3-270m-it  (mode=chat, type=chat)

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: meta-llama/Llama-3.2-1B-Instruct  (mode=chat, type=chat)

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: meta-llama/Llama-3.2-3B-Instruct  (mode=chat, type=chat)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: microsoft/MediPhi-Instruct  (mode=chat, type=chat)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: microsoft/Phi-4-mini-instruct  (mode=chat, type=chat)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: Qwen/Qwen3-1.7B  (mode=chat, type=chat)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Evaluating model: Qwen/Qwen3-4B  (mode=chat, type=chat)

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Device set to use cuda:0

Processing questions:   0%|          | 0/72 [00:00<?, ?it/s]

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1
Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

✓ Model evaluation complete. Results saved to: results/phq_clm_results.csv

======================================================================
Calculating Content Validity Metrics (all models)
======================================================================

✓ Content validity metrics saved to: results/linguistic_acceptability.csv

Content Validity Results:
        semantic_similarity  cola_score  silhouette_score
Q
PHQ9Q5             0.752692    0.878448          0.134678
PHQ9Q9             0.581778    0.903856          0.156755
PHQ9Q8             0.772080    0.884025          0.162483
PHQ9Q1             0.763613    0.868805          0.261065
PHQ9Q2             0.702211    0.942002          0.281749
PHQ9Q6             0.625567    0.843339          0.287118
PHQ9Q7             0.674884    0.762121          0.301841
PHQ9Q4             0.734302    0.951003          0.311966
PHQ9Q3             0.755090    0.881840          0.582734

======================================================================
Calculating Internal Consistency (Cronbach's Alpha, all models)
======================================================================

Cronbach Alpha:
Q: (0.8227364431766964, array([0.648, 0.931]))

phq Overall: (0.8227364431766964, array([0.648, 0.931]))

======================================================================
Calculating Factor Correlations (all models)
======================================================================

✓ Factor correlations (spearman):
       Q  phq
Q      -  ***
phq  1.0    -

======================================================================
Validation Complete!
======================================================================
Results saved in: results

In [9]:
results.keys()

dict_keys(['results_csv', 'content_validity', 'cronbach_alpha', 'correlations'])

In [10]:
results_csv = results['results_csv']

In [14]:
from pathlib import Path

p = Path('results/phq_clm_results.csv')

In [15]:
import pandas as pd
df = pd.read_csv(p)
len(set(df["model"]))

15

In [16]:
set(df["model"])

{'Qwen/Qwen2.5-3B',
 'Qwen/Qwen3-1.7B',
 'Qwen/Qwen3-4B',
 'google/gemma-2-2b',
 'google/gemma-3-1b-it',
 'google/gemma-3-270m',
 'google/gemma-3-270m-it',
 'meta-llama/Llama-3.2-1B',
 'meta-llama/Llama-3.2-1B-Instruct',
 'meta-llama/Llama-3.2-3B',
 'meta-llama/Llama-3.2-3B-Instruct',
 'microsoft/MediPhi',
 'microsoft/MediPhi-Instruct',
 'microsoft/MediPhi-PubMed',
 'microsoft/Phi-4-mini-instruct'}

## Analysis - base models

In [17]:
content_validity_base = validator.calc_content_validity(results_csv, model_type='base')
content_validity_base

✓ Content validity metrics (base) saved to: results/linguistic_acceptability_base.csv

        semantic_similarity  cola_score  silhouette_score
Q
PHQ9Q9             0.581778    0.903856          0.144415
PHQ9Q8             0.772080    0.884025          0.157760
PHQ9Q5             0.752692    0.878448          0.169000
PHQ9Q7             0.674884    0.762121          0.227770
PHQ9Q4             0.734302    0.951003          0.294768
PHQ9Q2             0.702211    0.942002          0.317876
PHQ9Q1             0.763613    0.868805          0.337203
PHQ9Q6             0.625567    0.843339          0.353229
PHQ9Q3             0.755090    0.881840          0.633824

In [18]:
alpha_base = validator.calc_cronbach_alpha(results_csv, model_type='base')
print('overall:', alpha_base['overall'])
print('factors:', alpha_base['factors'])

Cronbach Alpha (base):
Q: (0.7855767436702157, array([0.424, 0.957]))

phq Overall (base): (0.7855767436702157, array([0.424, 0.957]))
overall: (0.7855767436702157, array([0.424, 0.957]))
factors: {'Q': (0.7855767436702157, array([0.424, 0.957]))}

In [19]:
validator.test_question_affect_on_cronbach_alpha(alpha_base['data_df'])

All Questions Alpha: (0.7855767436702157, array([0.424, 0.957]))
without: PHQ9Q1 Alpha: (0.7627579594113694, array([0.353, 0.953]))
without: PHQ9Q2 Alpha: (0.7083822492907128, array([0.205, 0.942]))
without: PHQ9Q3 Alpha: (0.6602514843743141, array([0.073, 0.932]))
without: PHQ9Q4 Alpha: (0.7157198535432827, array([0.225, 0.943]))
without: PHQ9Q5 Alpha: (0.8240239598685696, array([0.52 , 0.965]))
without: PHQ9Q6 Alpha: (0.7742348733261565, array([0.384, 0.955]))
without: PHQ9Q7 Alpha: (0.696597108217393, array([0.173, 0.939]))
without: PHQ9Q8 Alpha: (0.8301211245486907, array([0.537, 0.966]))
without: PHQ9Q9 Alpha: (0.8084598799222256, array([0.478, 0.962]))

In [20]:
correlations_base = validator.calc_correlations(results_csv, model_type='base')
correlations_base

✓ Factor correlations (base) (spearman):
       Q  phq
Q      -  ***
phq  1.0    -

       Q  phq
Q      -  ***
phq  1.0    -

## Analysis - instruct models

In [21]:
content_validity_chat = validator.calc_content_validity(results_csv, model_type='chat')
content_validity_chat

✓ Content validity metrics (chat) saved to: results/linguistic_acceptability_chat.csv

        semantic_similarity  cola_score  silhouette_score
Q
PHQ9Q5             0.752692    0.878448          0.104646
PHQ9Q8             0.772080    0.884025          0.166615
PHQ9Q9             0.581778    0.903856          0.167553
PHQ9Q1             0.763613    0.868805          0.194445
PHQ9Q6             0.625567    0.843339          0.229270
PHQ9Q2             0.702211    0.942002          0.250139
PHQ9Q4             0.734302    0.951003          0.327014
PHQ9Q7             0.674884    0.762121          0.366653
PHQ9Q3             0.755090    0.881840          0.538031

In [22]:
alpha_chat = validator.calc_cronbach_alpha(results_csv, model_type='chat')
print('overall:', alpha_chat['overall'])
print('factors:', alpha_chat['factors'])

Cronbach Alpha (chat):
Q: (0.9047920126763793, array([0.76 , 0.978]))

phq Overall (chat): (0.9047920126763791, array([0.76 , 0.978]))
overall: (0.9047920126763791, array([0.76 , 0.978]))
factors: {'Q': (0.9047920126763793, array([0.76 , 0.978]))}

In [23]:
validator.test_question_affect_on_cronbach_alpha(alpha_chat['data_df'])

All Questions Alpha: (0.9047920126763793, array([0.76 , 0.978]))
without: PHQ9Q1 Alpha: (0.9167810325760204, array([0.787, 0.981]))
without: PHQ9Q2 Alpha: (0.8833020494639203, array([0.701, 0.973]))
without: PHQ9Q3 Alpha: (0.8777878985789936, array([0.687, 0.971]))
without: PHQ9Q4 Alpha: (0.9046722830567017, array([0.756, 0.978]))
without: PHQ9Q5 Alpha: (0.8882830105987816, array([0.714, 0.974]))
without: PHQ9Q6 Alpha: (0.8840369028030701, array([0.703, 0.973]))
without: PHQ9Q7 Alpha: (0.8856204622690785, array([0.707, 0.973]))
without: PHQ9Q8 Alpha: (0.9130520356851781, array([0.778, 0.98 ]))
without: PHQ9Q9 Alpha: (0.8817083339130962, array([0.697, 0.972]))

In [24]:
correlations_chat = validator.calc_correlations(results_csv, model_type='chat')
correlations_chat

✓ Factor correlations (chat) (spearman):
       Q  phq
Q      -  ***
phq  1.0    -

       Q  phq
Q      -  ***
phq  1.0    -

## Item-level linguistic metrics (model-independent)

In [25]:
semantic_results = validator.get_semantic_similarity()
cola_results = validator.get_cola_score()

Calculating semantic similarity:   0%|          | 0/9 [00:00<?, ?it/s]

Calculating COLA scores:   0%|          | 0/9 [00:00<?, ?it/s]

In [26]:
cola_results

        cola_score
PHQ9Q1    0.868805
PHQ9Q2    0.942002
PHQ9Q3    0.881840
PHQ9Q4    0.951003
PHQ9Q5    0.878448
PHQ9Q6    0.843339
PHQ9Q7    0.762121
PHQ9Q8    0.884025
PHQ9Q9    0.903856

In [27]:
semantic_results

        semantic_similarity
PHQ9Q1             0.763613
PHQ9Q2             0.702211
PHQ9Q3             0.755090
PHQ9Q4             0.734302
PHQ9Q5             0.752692
PHQ9Q6             0.625567
PHQ9Q7             0.674884
PHQ9Q8             0.772080
PHQ9Q9             0.581778